In [4]:
import pandas as pd

data = {
    "Student": ["Ali", "Vali", "Sami", "Lola", "Nodir",
                "Aziza", "Jasur", "Malika", "Timur", "Zarina"],

    "Group": ["A", "B", "A", "B", "A",
              "B", "A", "B", "A", "B"],

    "Subject": ["Math", "Math", "English", "English", "Math",
                "English", "Math", "Math", "English", "English"],

    "Score": [85, 67, 90, 74, 58,
              88, 95, 60, 77, 82],

    "Attendance": [90, 75, 95, 80, 60,
                   92, 98, 70, 85, 88]
}

data = pd.DataFrame(data)

data

  Student Group  Subject  Score  Attendance
0     Ali     A     Math     85          90
1    Vali     B     Math     67          75
2    Sami     A  English     90          95
3    Lola     B  English     74          80
4   Nodir     A     Math     58          60
5   Aziza     B  English     88          92
6   Jasur     A     Math     95          98
7  Malika     B     Math     60          70
8   Timur     A  English     77          85
9  Zarina     B  English     82          88

In [ ]:
data[data['Score'] > 80]

  Student Group  Subject  Score  Attendance
0     Ali     A     Math     85          90
2    Sami     A  English     90          95
5   Aziza     B  English     88          92
6   Jasur     A     Math     95          98
9  Zarina     B  English     82          88

In [8]:
data[['Student', 'Subject', 'Score']]

  Student  Subject  Score
0     Ali     Math     85
1    Vali     Math     67
2    Sami  English     90
3    Lola  English     74
4   Nodir     Math     58
5   Aziza  English     88
6   Jasur     Math     95
7  Malika     Math     60
8   Timur  English     77
9  Zarina  English     82

In [9]:
data.groupby('Group', as_index=False).agg(AverageScore=('Score', 'mean'))

  Group  AverageScore
0     A          81.0
1     B          74.2

In [12]:
result = (
    data.groupby('Subject', as_index=False)
    .agg(
        MaxScore=('Score', 'max'),
        AverageAttendance=('Attendance', 'mean')
    )
)

result

   Subject  MaxScore  AverageAttendance
0  English        90               88.0
1     Math        95               78.6

In [14]:
result = (
    data[data['Attendance'] > 80].groupby('Group', as_index=False)
    .agg(StudentCount=('Student', 'count'))
)

result

  Group  StudentCount
0     A             4
1     B             2

In [6]:
from sqlalchemy import create_engine

engine = create_engine(r'sqlite:///data\chinook.db')

In [7]:
genres = pd.read_sql_table('genres', engine)

tracks = pd.read_sql_table('tracks', engine)

genres

    GenreId                Name
0         1                Rock
1         2                Jazz
2         3               Metal
3         4  Alternative & Punk
4         5       Rock And Roll
5         6               Blues
6         7               Latin
7         8              Reggae
8         9                 Pop
9        10          Soundtrack
10       11          Bossa Nova
11       12      Easy Listening
12       13         Heavy Metal
13       14            R&B/Soul
14       15   Electronica/Dance
15       16               World
16       17         Hip Hop/Rap
17       18     Science Fiction
18       19            TV Shows
19       20    Sci Fi & Fantasy
20       21               Drama
21       22              Comedy
22       23         Alternative
23       24           Classical
24       25               Opera

In [12]:
genres.merge(tracks, on='GenreId').groupby('Name_x').agg({"TrackId":'count'})\
    .rename(columns={'TrackId':'Number of Tracks'}).sort_values(by='Number of Tracks', ascending=False).head()

                    Number of Tracks
Name_x
Rock                            1297
Latin                            579
Metal                            374
Alternative & Punk               332
Jazz                             130