data = {
    "Student": ["Ali", "Vali", "Sami", "Lola", "Nodir",
                "Aziza", "Jasur", "Malika", "Timur", "Zarina"],

    "Group": ["A", "B", "A", "B", "A",
              "B", "A", "B", "A", "B"],

    "Subject": ["Math", "Math", "English", "English", "Math",
                "English", "Math", "Math", "English", "English"],

    "Score": [85, 67, 90, 74, 58,
              88, 95, 60, 77, 82],

    "Attendance": [90, 75, 95, 80, 60,
                   92, 98, 70, 85, 88]
}


Task 1

Score ustuni 80 dan katta bo'lgan o'quvchilarni chiqaring.

Task 2

Faqat quyidagi ustunlarni chiqaring:

- Student

- Subject

- Score

Task 3

Har bir Group bo'yicha o'rtacha score ni hisoblang.

Task 4

Har bir Subject bo'yicha:

- eng katta score
- o'rtacha attendance

ni hisoblang.

Task 5

Attendance 80 dan katta bo'lgan o'quvchilarni Group bo'yicha guruhlab, har bir groupda nechta student borligini hisoblang.

In [1]:
import pandas as pd

data = {
    "Student": ["Ali", "Vali", "Sami", "Lola", "Nodir",
                "Aziza", "Jasur", "Malika", "Timur", "Zarina"],

    "Group": ["A", "B", "A", "B", "A",
              "B", "A", "B", "A", "B"],

    "Subject": ["Math", "Math", "English", "English", "Math",
                "English", "Math", "Math", "English", "English"],

    "Score": [85, 67, 90, 74, 58,
              88, 95, 60, 77, 82],

    "Attendance": [90, 75, 95, 80, 60,
                   92, 98, 70, 85, 88]
}

df = pd.DataFrame(data)
df

  Student Group  Subject  Score  Attendance
0     Ali     A     Math     85          90
1    Vali     B     Math     67          75
2    Sami     A  English     90          95
3    Lola     B  English     74          80
4   Nodir     A     Math     58          60
5   Aziza     B  English     88          92
6   Jasur     A     Math     95          98
7  Malika     B     Math     60          70
8   Timur     A  English     77          85
9  Zarina     B  English     82          88

In [6]:
df[df['Score'] > 80]

  Student Group  Subject  Score  Attendance
0     Ali     A     Math     85          90
2    Sami     A  English     90          95
5   Aziza     B  English     88          92
6   Jasur     A     Math     95          98
9  Zarina     B  English     82          88

In [7]:
df[['Student', 'Subject', 'Score']]

  Student  Subject  Score
0     Ali     Math     85
1    Vali     Math     67
2    Sami  English     90
3    Lola  English     74
4   Nodir     Math     58
5   Aziza  English     88
6   Jasur     Math     95
7  Malika     Math     60
8   Timur  English     77
9  Zarina  English     82

In [9]:
df.groupby('Group').agg(Avg_score = ('Score','mean'))

       Avg_score
Group
A           81.0
B           74.2

In [10]:
df.groupby('Subject').agg({'Score': 'max', 'Attendance':'mean'})

         Score  Attendance
Subject
English     90        88.0
Math        95        78.6

In [ ]:
df[df['Attendance'].gt(80)].groupby('Group')['Student'].count()

Group
A    4
B    2
Name: Student, dtype: int64

In [14]:
df[df['Attendance'].gt(80)].groupby('Group').agg(student_count = ('Student', 'count'))

       student_count
Group
A                  4
B                  2

## Pandas-4 Combining Objects

In [15]:
names = pd.read_csv('data/names.csv')
names

       Name  Age
0  Cornelia   70
1     Abbas   69
2  Penelope    4
3      Niko    2

In [16]:
names.iloc[2]

Name    Penelope
Age            4
Name: 2, dtype: object

In [ ]:
names.loc[15]

Name    Penelope
Age            4
Name: 2, dtype: object

In [24]:
names.iloc[15] = ['Ali', 20]

IndexError: iloc cannot enlarge its target object

In [25]:
names.loc[15] = ['Ali', 20]

In [26]:
names

        Name  Age
0   Cornelia   70
1      Abbas   69
2   Penelope    4
3       Niko    2
15       Ali   20

In [27]:
names.loc[15]

Name    Ali
Age      20
Name: 15, dtype: object

In [29]:
names.iloc[4]

Name    Ali
Age      20
Name: 15, dtype: object

In [30]:
names.iloc[5] = ['Vali', 25]

IndexError: iloc cannot enlarge its target object

In [31]:
names.loc['abc'] = ['Akbar', 30]
names

         Name  Age
0    Cornelia   70
1       Abbas   69
2    Penelope    4
3        Niko    2
15        Ali   20
abc     Akbar   30

In [32]:
names.iloc[5]

Name    Akbar
Age        30
Name: abc, dtype: object

In [33]:
names.loc['abc']

Name    Akbar
Age        30
Name: abc, dtype: object

In [37]:
names.drop('abc', inplace=True)

In [38]:
names

        Name  Age
0   Cornelia   70
1      Abbas   69
2   Penelope    4
3       Niko    2
15       Ali   20

In [43]:
names.drop(3)

        Name  Age
0   Cornelia   70
1      Abbas   69
2   Penelope    4
15       Ali   20

In [45]:
names

        Name  Age
0   Cornelia   70
1      Abbas   69
2   Penelope    4
3       Niko    2
15       Ali   20

In [44]:
len(names)

5

In [46]:
names.loc[len(names)] = ['Asror', 30]
names

        Name  Age
0   Cornelia   70
1      Abbas   69
2   Penelope    4
3       Niko    2
15       Ali   20
5      Asror   30

In [48]:
names.loc[len(names)] = ['Asilbek', None]

In [49]:
names

        Name  Age
0   Cornelia   70
1      Abbas   69
2   Penelope    4
3       Niko    2
15       Ali   20
5      Asror   30
6    Asilbek  NaN

In [50]:
import numpy as np

In [51]:
names.loc[len(names)] = ['Asilbek', np.nan]

In [52]:
names

        Name  Age
0   Cornelia   70
1      Abbas   69
2   Penelope    4
3       Niko    2
15       Ali   20
5      Asror   30
6    Asilbek  NaN
7    Asilbek  NaN

In [54]:
stocks_2016 = pd.read_csv('data/stocks_2016.csv')
stocks_2017 = pd.read_csv('data/stocks_2017.csv')
stocks_2018 = pd.read_csv('data/stocks_2018.csv')

In [55]:
stocks_2016

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70

In [56]:
stocks_2017

  Symbol  Shares  Low  High
0   AAPL      50  120   140
1     GE     100   30    40
2    IBM      87   75    95
3    SLB      20   55    85
4    TXN     500   15    23
5   TSLA     100  100   300

In [ ]:
# concat -> pandas funksiyasi hisoblanadi = SQLdagi union all

In [58]:
pd.concat([stocks_2016, stocks_2017], keys=['2016', '2017'])

       Symbol  Shares  Low  High
2016 0   AAPL      80   95   110
     1   TSLA      50   80   130
     2    WMT      40   55    70
2017 0   AAPL      50  120   140
     1     GE     100   30    40
     2    IBM      87   75    95
     3    SLB      20   55    85
     4    TXN     500   15    23
     5   TSLA     100  100   300

In [83]:
result = pd.concat([stocks_2016, stocks_2017], names=['Years', 'Default Index'], keys=['2016', '2017'])

In [81]:
result

                    Symbol  Shares  Low  High
Years Default Index
2016  0               AAPL      80   95   110
      1               TSLA      50   80   130
      2                WMT      40   55    70
2017  0               AAPL      50  120   140
      1                 GE     100   30    40
      2                IBM      87   75    95
      3                SLB      20   55    85
      4                TXN     500   15    23
      5               TSLA     100  100   300

In [79]:
result.iloc[4]

Symbol     GE
Shares    100
Low        30
High       40
Name: (2017, 1), dtype: object

In [85]:
pd.concat([stocks_2016, stocks_2017], keys=['2016', '2017'], names=['Years', 'Default Index'], axis=1)

Years           2016                       2017
Default Index Symbol Shares   Low   High Symbol Shares  Low High
0               AAPL   80.0  95.0  110.0   AAPL     50  120  140
1               TSLA   50.0  80.0  130.0     GE    100   30   40
2                WMT   40.0  55.0   70.0    IBM     87   75   95
3                NaN    NaN   NaN    NaN    SLB     20   55   85
4                NaN    NaN   NaN    NaN    TXN    500   15   23
5                NaN    NaN   NaN    NaN   TSLA    100  100  300

In [86]:
pd.concat([stocks_2016, stocks_2017], keys=['2016', '2017'], names=['Years', 'Default Index'], axis=1).fillna('Unknown')

Years             2016                              2017
Default Index   Symbol   Shares      Low     High Symbol Shares  Low High
0                 AAPL     80.0     95.0    110.0   AAPL     50  120  140
1                 TSLA     50.0     80.0    130.0     GE    100   30   40
2                  WMT     40.0     55.0     70.0    IBM     87   75   95
3              Unknown  Unknown  Unknown  Unknown    SLB     20   55   85
4              Unknown  Unknown  Unknown  Unknown    TXN    500   15   23
5              Unknown  Unknown  Unknown  Unknown   TSLA    100  100  300

In [ ]:
years = (2016, 2017, 2018)

In [88]:
type(years)

tuple

In [94]:
all_stocks = for x in years:
    print(pd.read_csv(f'data/stocks_{x}.csv'))

SyntaxError: invalid syntax (4100093188.py, line 1)

In [95]:
all_stocks = [pd.read_csv(f'data/stocks_{x}.csv') for x in years]
all_stocks

[  Symbol  Shares  Low  High
 0   AAPL      80   95   110
 1   TSLA      50   80   130
 2    WMT      40   55    70,
   Symbol  Shares  Low  High
 0   AAPL      50  120   140
 1     GE     100   30    40
 2    IBM      87   75    95
 3    SLB      20   55    85
 4    TXN     500   15    23
 5   TSLA     100  100   300,
   Symbol  Shares  Low  High
 0   AAPL      40  135   170
 1   AMZN       8  900  1125
 2   TSLA      50  220   400]

In [97]:
pd.concat(all_stocks, keys=[2016, 2017, 2018])

       Symbol  Shares  Low  High
2016 0   AAPL      80   95   110
     1   TSLA      50   80   130
     2    WMT      40   55    70
2017 0   AAPL      50  120   140
     1     GE     100   30    40
     2    IBM      87   75    95
     3    SLB      20   55    85
     4    TXN     500   15    23
     5   TSLA     100  100   300
2018 0   AAPL      40  135   170
     1   AMZN       8  900  1125
     2   TSLA      50  220   400

In [ ]:
# join

In [98]:
stocks_2016

  Symbol  Shares  Low  High
0   AAPL      80   95   110
1   TSLA      50   80   130
2    WMT      40   55    70

In [99]:
stocks_2017

  Symbol  Shares  Low  High
0   AAPL      50  120   140
1     GE     100   30    40
2    IBM      87   75    95
3    SLB      20   55    85
4    TXN     500   15    23
5   TSLA     100  100   300

In [ ]:
stocks_2016.join(stocks_2017, lsuffix='_2016', rsuffix='_2017')   # index bo'yicha qo'shadi

,Symbol_2016,Shares_2016,Low_2016,High_2016,Symbol_2017,Shares_2017,Low_2017,High_2017
0,AAPL,80,95,110,AAPL,50,120,140
1,TSLA,50,80,130,GE,100,30,40
2,WMT,40,55,70,IBM,87,75,95

In [ ]:
stocks_2017.join(stocks_2016, lsuffix='_2017', rsuffix='_2016') # left join by default

,Symbol_2017,Shares_2017,Low_2017,High_2017,Symbol_2016,Shares_2016,Low_2016,High_2016
0,AAPL,50,120,140,AAPL,80.0,95.0,110.0
1,GE,100,30,40,TSLA,50.0,80.0,130.0
2,IBM,87,75,95,WMT,40.0,55.0,70.0
3,SLB,20,55,85,NaN,NaN,NaN,NaN
4,TXN,500,15,23,NaN,NaN,NaN,NaN
5,TSLA,100,100,300,NaN,NaN,NaN,NaN

In [106]:
stocks_2017.join(stocks_2016, lsuffix='_2017', rsuffix='_2016', how='inner')

,Symbol_2017,Shares_2017,Low_2017,High_2017,Symbol_2016,Shares_2016,Low_2016,High_2016
0,AAPL,50,120,140,AAPL,80,95,110
1,GE,100,30,40,TSLA,50,80,130
2,IBM,87,75,95,WMT,40,55,70

In [107]:
stocks_2017.join(stocks_2016, lsuffix='_2017', rsuffix='_2016', how='cross')

,Symbol_2017,Shares_2017,Low_2017,High_2017,Symbol_2016,Shares_2016,Low_2016,High_2016
0,AAPL,50,120,140,AAPL,80,95,110
1,AAPL,50,120,140,TSLA,50,80,130
2,AAPL,50,120,140,WMT,40,55,70
3,GE,100,30,40,AAPL,80,95,110
4,GE,100,30,40,TSLA,50,80,130
5,GE,100,30,40,WMT,40,55,70
6,IBM,87,75,95,AAPL,80,95,110
7,IBM,87,75,95,TSLA,50,80,130
8,IBM,87,75,95,WMT,40,55,70
9,SLB,20,55,85,AAPL,80,95,110
10,SLB,20,55,85,TSLA,50,80,130
11,SLB,20,55,85,WMT,40,55,70
12,TXN,500,15,23,AAPL,80,95,110
13,TXN,500,15,23,TSLA,50,80,130
14,TXN,500,15,23,WMT,40,55,70
15,TSLA,100,100,300,AAPL,80,95,110
16,TSLA,100,100,300,TSLA,50,80,130
17,TSLA,100,100,300,WMT,40,55,70

In [108]:
stocks_2017.join(stocks_2016, lsuffix='_2017', rsuffix='_2016', how='outer')

,Symbol_2017,Shares_2017,Low_2017,High_2017,Symbol_2016,Shares_2016,Low_2016,High_2016
0,AAPL,50,120,140,AAPL,80.0,95.0,110.0
1,GE,100,30,40,TSLA,50.0,80.0,130.0
2,IBM,87,75,95,WMT,40.0,55.0,70.0
3,SLB,20,55,85,NaN,NaN,NaN,NaN
4,TXN,500,15,23,NaN,NaN,NaN,NaN
5,TSLA,100,100,300,NaN,NaN,NaN,NaN

In [109]:
stocks_2017.join(stocks_2016, lsuffix='_2017', rsuffix='_2016', how='right')

,Symbol_2017,Shares_2017,Low_2017,High_2017,Symbol_2016,Shares_2016,Low_2016,High_2016
0,AAPL,50,120,140,AAPL,80,95,110
1,GE,100,30,40,TSLA,50,80,130
2,IBM,87,75,95,WMT,40,55,70

In [113]:
stocks_2016.set_index('Symbol', inplace=True)

In [114]:
stocks_2016

        Shares  Low  High
Symbol
AAPL        80   95   110
TSLA        50   80   130
WMT         40   55    70

In [115]:
stocks_2017.set_index('Symbol', inplace=True)

In [116]:
stocks_2017

        Shares  Low  High
Symbol
AAPL        50  120   140
GE         100   30    40
IBM         87   75    95
SLB         20   55    85
TXN        500   15    23
TSLA       100  100   300

In [117]:
stocks_2017.join(stocks_2016, lsuffix='_2017', rsuffix='_2016')

        Shares_2017  Low_2017  High_2017  Shares_2016  Low_2016  High_2016
Symbol
AAPL             50       120        140         80.0      95.0      110.0
GE              100        30         40          NaN       NaN        NaN
IBM              87        75         95          NaN       NaN        NaN
SLB              20        55         85          NaN       NaN        NaN
TXN             500        15         23          NaN       NaN        NaN
TSLA            100       100        300         50.0      80.0      130.0

In [118]:
stocks_2017.join(stocks_2016, lsuffix='_2017', rsuffix='_2016', how ='inner')

        Shares_2017  Low_2017  High_2017  Shares_2016  Low_2016  High_2016
Symbol
AAPL             50       120        140           80        95        110
TSLA            100       100        300           50        80        130

In [119]:
stocks_2017.join(stocks_2016, lsuffix='_2017', rsuffix='_2016', how ='right')

        Shares_2017  Low_2017  High_2017  Shares_2016  Low_2016  High_2016
Symbol
AAPL           50.0     120.0      140.0           80        95        110
TSLA          100.0     100.0      300.0           50        80        130
WMT             NaN       NaN        NaN           40        55         70

In [ ]:
# merge - inner joinda ishlidi, columnlar bo'yicha birlashtirish imkoni bor

In [120]:
stocks_2016

        Shares  Low  High
Symbol
AAPL        80   95   110
TSLA        50   80   130
WMT         40   55    70

In [121]:
stocks_2017

        Shares  Low  High
Symbol
AAPL        50  120   140
GE         100   30    40
IBM         87   75    95
SLB         20   55    85
TXN        500   15    23
TSLA       100  100   300

In [130]:
stocks_2016.merge(stocks_2017, on = 'Shares', how='left', suffixes=['_', ' '])

   Shares  Low_  High_   Low   High
0      80    95    110    NaN    NaN
1      50    80    130  120.0  140.0
2      40    55     70    NaN    NaN

In [131]:
food_name = ['prices.csv', 'transactions.csv']
food_info = [pd.read_csv(f'data/food_{x}') for x in food_name]

In [132]:
food_info

[     item store  price  Date
 0    pear     A   0.99  2017
 1    pear     B   1.99  2017
 2   peach     A   2.99  2017
 3   peach     B   3.49  2017
 4  banana     A   0.39  2017
 5  banana     B   0.49  2017
 6   steak     A   5.99  2017
 7   steak     B   6.99  2017
 8   steak     B   4.99  2015,
    custid     item store  quantity
 0       1     pear     A         5
 1       1   banana     A        10
 2       2    steak     B         3
 3       2     pear     B         1
 4       2    peach     B         2
 5       2    steak     B         1
 6       2  coconut     B         4]

In [133]:
food_prices, food_transactions = food_info

In [134]:
food_prices

     item store  price  Date
0    pear     A   0.99  2017
1    pear     B   1.99  2017
2   peach     A   2.99  2017
3   peach     B   3.49  2017
4  banana     A   0.39  2017
5  banana     B   0.49  2017
6   steak     A   5.99  2017
7   steak     B   6.99  2017
8   steak     B   4.99  2015

In [135]:
food_transactions

   custid     item store  quantity
0       1     pear     A         5
1       1   banana     A        10
2       2    steak     B         3
3       2     pear     B         1
4       2    peach     B         2
5       2    steak     B         1
6       2  coconut     B         4

In [138]:
food_prices.merge(food_transactions, on='item', how='right')

       item store_x  price    Date  custid store_y  quantity
0      pear       A   0.99  2017.0       1       A         5
1      pear       B   1.99  2017.0       1       A         5
2    banana       A   0.39  2017.0       1       A        10
3    banana       B   0.49  2017.0       1       A        10
4     steak       A   5.99  2017.0       2       B         3
5     steak       B   6.99  2017.0       2       B         3
6     steak       B   4.99  2015.0       2       B         3
7      pear       A   0.99  2017.0       2       B         1
8      pear       B   1.99  2017.0       2       B         1
9     peach       A   2.99  2017.0       2       B         2
10    peach       B   3.49  2017.0       2       B         2
11    steak       A   5.99  2017.0       2       B         1
12    steak       B   6.99  2017.0       2       B         1
13    steak       B   4.99  2015.0       2       B         1
14  coconut     NaN    NaN     NaN       2       B         4

In [147]:
from sqlalchemy import create_engine

engine = create_engine(r'sqlite:///C:\Users\PC\Desktop\F64_Python\lesson20\data\chinook.db')

In [148]:
genres = pd.read_sql_table('genres', engine)

In [149]:
genres

    GenreId                Name
0         1                Rock
1         2                Jazz
2         3               Metal
3         4  Alternative & Punk
4         5       Rock And Roll
5         6               Blues
6         7               Latin
7         8              Reggae
8         9                 Pop
9        10          Soundtrack
10       11          Bossa Nova
11       12      Easy Listening
12       13         Heavy Metal
13       14            R&B/Soul
14       15   Electronica/Dance
15       16               World
16       17         Hip Hop/Rap
17       18     Science Fiction
18       19            TV Shows
19       20    Sci Fi & Fantasy
20       21               Drama
21       22              Comedy
22       23         Alternative
23       24           Classical
24       25               Opera

In [150]:
tracks = pd.read_sql_table('tracks', engine)

In [151]:
tracks

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,NaN,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
...,...,...,...,...,...,...,...,...,...
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,NaN,286741,4718950,0.99
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,Claudio Monteverdi,66639,1189062,0.99
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99
3502,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99

In [ ]:
# har bir genreda nechta track bor ekanligini topish kerak

In [159]:
genres.merge(tracks, on='GenreId').groupby('Name_x').agg({"TrackId":'count'})\
    .rename(columns={'TrackId':'Number of Tracks'}).sort_values(by='Number of Tracks', ascending=False).head()

                    Number of Tracks
Name_x
Rock                            1297
Latin                            579
Metal                            374
Alternative & Punk               332
Jazz                             130

In [ ]:
# concat - union (funksiya (pd.concat()))
# join - left join (index bo'yicha bog'lab beradi)
# merge - inner join(ustunlar bo'yicha bog'lab beradi)