## Homework - 23 Web Scraping

Using Python web scraping tools, extract the following information from the provided Rotten Tomatoes page:

- Cartoon/Movie Name
- Release Year
- Tomatometer Score
- Rank

Requirements:
1. Scrape all available records from the page.
2. Store the extracted data in a Pandas DataFrame.
3. Create a SQLite database named 'Cartoon.db'.
4. Save the DataFrame into a table named 'Cartoons'.
5. Verify that the data has been successfully inserted into the database.

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup


url = "https://editorial.rottentomatoes.com/guide/movies-100-percent-score-rotten-tomatoes/"

response = requests.get(url)
response.status_code

200

### 1. Scrape all available records from the page.

In [4]:
html_content = response.text
soup = BeautifulSoup(html_content, "html.parser")
print(soup.prettify())

<!DOCTYPE html>
<html lang="en-US">
 <head prefix="og: http://ogp.me/ns# flixstertomatoes: http://ogp.me/ns/apps/flixstertomatoes#">
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <script src="https://www.rottentomatoes.com/rt-common.js?single">
  </script>
  <script id="rt-feature-flags-json" type="application/json">
   {"adsCarouselHP":"false","adsCarouselHPSlug":"rt-sponsored-carousel-list-disney-plus-throwbacks-campaign","adsCarouselOP":"false","adsCarouselOPSlug":"rt-sponsored-carousel-list-disney-plus-throwbacks-campaign","adsMockDLP":"false","adsPages":"none","adsSponsoredOverrideOP":"true","adsSponsoredOverrideOPSlugs":"rt-sponsored-override-op-starz","adsVideoSpotlightHP":"false","adsVideoSpotlightHPv2":"false","artiEnabled":"true","artiSearchNavEnabled":"true","authVerboseLogs":"false","bypassCriticValidationEnabled":"false","criticPublicationProfile2026Q1Enabled":"true","editorialApiDisabled":"false","fandangoConsolidation2026Q2Enabled":"true","legacyBridge":"true","logVerboseEnabled":"false","mobileAppAndroid":"https:\/\/play.google.com\/store\/apps\/details?id=com.rottentomatoes.android","mobileAppIos":"https:\/\/apps.apple.com\/us\/app\/rotten-tomatoes-movies-tv\/id6673916573","mobileAppIosMeta":"app-id=6673916573","rtebProxyEnabled":"false","trafficAndroidEnabled":"true","trafficSafariEnabled":"true","communityWatch2026Q3Enabled":"false","adAdjustment2026Q3Enabled":"false"}
  </script>
  <!-- OneTrust Cookies Consent Notice start for rottentomatoes.com -->
  <script charset="UTF-8" crossorigin="anonymous" data-domain-script="01978557-1604-76a7-ad7c-18216757cf52" integrity="sha384-ZSwMA1OqSOznvxMtYdWlw0CUYqxpHjUOjfz9IcOnQUXvWoX7QfD7wjN7tgv+SpLT" src="https://cdn.cookielaw.org/consent/01978557-1604-76a7-ad7c-18216757cf52/otSDKStub.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   function OptanonWrapper() { }
  </script>
  <!-- OneTrust Cookies Consent Notice end for rottentomatoes.com -->
  <!-- OneTrust IAB US Privacy (USP) -->
  <script ccpa-opt-out-geo="US" ccpa-opt-out-ids="USP" ccpa-opt-out-lspa="false" charset="UTF-8" src="https://cdn.cookielaw.org/opt-out/otCCPAiab.js" type="text/javascript">
  </script>
  <!-- OneTrust IAB US Privacy (USP) end -->
  <meta content="app-id=6673916573" name="apple-itunes-app"/>
  <meta content="From 12 Angry Men and Toy Story to The Terminator and Pinocchio, these are the Certified Fresh movies that also boast a perfect Tomatometer score!" property="og.description"/>
  <meta content="From 12 Angry Men and Toy Story to The Terminator and Pinocchio, these are the Certified Fresh movies that also boast a perfect Tomatometer score!" name="description"/>
  <meta content="The 100% Club: Movies With a 100% Tomatometer Score on Rotten Tomatoes" property="og:title"/>
  <meta content="article" property="og:type"/>
  <meta content="https://editorial.rottentomatoes.com/wp-content/uploads/2024/11/600WallaceGromit2.jpg?w=600" property="og:image"/>
  <meta content="https://editorial.rottentomatoes.com/guide/movies-100-percent-score-rotten-tomatoes/" property="og:url"/>
  <meta content="166676" name="editorialID"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="@rottentomatoes" name="twitter:site"/>
  <meta content="The 100% Club: Movies With a 100% Tomatometer Score on Rotten Tomatoes" name="twitter:title"/>
  <meta content="From 12 Angry Men and Toy Story to The Terminator and Pinocchio, these are the Certified Fresh movies that also boast a perfect Tomatometer score!" name="twitter:description"/>
  <meta content="https://editorial.rottentomatoes.com/wp-content/uploads/2024/11/600WallaceGromit2.jpg?w=600" name="twitter:image"/>
  <title>
   The 100% Club: Movies With a 100% Tomatometer Score on Rotten Tomatoes							 | 	Rotten Tomatoes
  </title>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link href="https://editorial.rottentomatoes.com/xmlrpc.php" rel="pingback"/>
  <link href="https://editorial.rottentomatoes.com/wp-content/themes/rt-editorial/assets/images/favicon.ico" rel="icon" type="image/x-icon"/>
  <script>
   // Push column to dataLayer
		var dataLayer = dataLayer || [];

		dataLayer.push({
			"post-url": "https:\/\/editorial.rottentomatoes.com\/guide\/movies-100-percent-score-rotten-tomatoes\/",
			"column": "0",
			"hub":0,
			"author": "alex-vo",
			"related-tv-series-ids": [],
			"related-movie-ids": [],
			"publication-date": "10\/24\/2025",
			"related-celebrity-ids": [],
			"tags": ""		});
  </script>
  <script>
   var BK = {};
		BK.PageName="https:\/\/editorial.rottentomatoes.com\/guide\/movies-100-percent-score-rotten-tomatoes\/";
		BK.SiteSection="guide";
		BK.ArticleTags="";
		BK.RelatedMovieId=[];
		BK.RelatedTalentId=[];
		BK.RelatedTVSeriesId=[];

		var mpscall = mpscall || {};
		mpscall = {
			"site":"rottentomatoes-web",
			"field[env]": "production", // Execution environment.
			"type": "guide",
			"cat": "article|home"		};
		var mpsopts = {
			"host": "app.mps.vsnt.net",
			"updatecorrelator": true
		}
		var mps=mps||{};mps._ext=mps._ext||{};mps._adsheld=[];mps._queue=mps._queue||{};mps._queue.mpsloaded=mps._queue.mpsloaded||[];mps._queue.mpsinit=mps._queue.mpsinit||[];mps._queue.gptloaded=mps._queue.gptloaded||[];mps._queue.adload=mps._queue.adload||[];mps._queue.adclone=mps._queue.adclone||[];mps._queue.adview=mps._queue.adview||[];mps._queue.refreshads=mps._queue.refreshads||[];mps.__timer=Date.now();mps.__intcode="v2";if(typeof mps.getAd!="function")mps.getAd=function(adunit){if(typeof adunit!="string")return false;var slotid="mps-getad-"+adunit.replace(/\W/g,"");if(!mps._ext||!mps._ext.loaded){mps._queue.gptloaded.push(function(){typeof mps._gptfirst=="function"&&mps._gptfirst(adunit,slotid);mps.cloneAd("#"+slotid,adunit)});mps._adsheld.push(adunit)}return'<div id="'+slotid+'" class="mps-wrapper" data-mps-fill-slot="'+adunit+'"></div>'};(function(){head=document.head||document.getElementsByTagName("head")[0],mpsload=document.createElement("script");mpsload.src="//"+mpsopts.host+"/fetch/ext/load-"+mpscall.site+".js?nowrite=2";mpsload.id="mps-load";head.insertBefore(mpsload,head.firstChild)})();

    var RottenTomatoes = RottenTomatoes || {};
    RottenTomatoes.context = { 'gptSite': "guide" };
  </script>
  <script type="text/javascript">
   var RT = RT || {};
		RT.buildHash = "898d4bef";
		RT.rtWeb = "https://www.rottentomatoes.com";
		RT.rtBridge = "https://www.rottentomatoes.com";
    RT.rtAssets = "https://editorial.rottentomatoes.com/wp-content/themes/rt-editorial";
		RT.buildCache = function(path) {
			try {
				if (!RT.buildHash) return path;

				const glue = path.includes('?') ? '&' : '?';
				return `${path}${glue}b=${RT.buildHash}`;
			} catch (err) {
				return path;
			}
		}

		var googletag = googletag || {};
		googletag.cmd = googletag.cmd || [];
		googletag.unitIds = [];
  </script>
  <meta content="max-image-preview:large" name="robots"/>
  <link href="//assets.adobedtm.com" rel="dns-prefetch"/>
  <link href="//ajax.googleapis.com" rel="dns-prefetch"/>
  <link href="https://editorial.rottentomatoes.com/guide/movies-100-percent-score-rotten-tomatoes/feed/" rel="alternate" title="Rotten Tomatoes » The 100% Club: Movies With a 100% Tomatometer Score on Rotten Tomatoes Comments Feed" type="application/rss+xml"/>
  <link href="https://editorial.rottentomatoes.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Feditorial.rottentomatoes.com%2Fguide%2Fmovies-100-percent-score-rotten-tomatoes%2F" rel="alternate" title="oEmbed (JSON)" type="application/json+oembed"/>
  <link href="https://editorial.rottentomatoes.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Feditorial.rottentomatoes.com%2Fguide%2Fmovies-100-percent-score-rotten-tomatoes%2F&amp;format=xml" rel="alternate" title="oEmbed (XML)" type="text/xml+oembed"/>
  <style id="wp-img-auto-sizes-contain-inline-css">
   img:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}
/*# sourceURL=wp-img-auto-sizes-contain-inline-css */
  </style>
  <style id="wp-emoji-styles-inline-css">
   img.wp-smiley, img.emoji {
		display: inline !important;
		border: none !important;
		box-shadow: none !important;
		height: 1em !important;
		width: 1em !important;
		margin: 0 0.07em !important;
		vertical-align: -0.1em !important;
		background: none !important;
		padding: 0 !important;
	}
/*# sourceURL=wp-emoji-styles-inline-css */
  </style>
  <style id="wp-block-library-inline-css">
   :root{--wp-block-synced-color:#7a00df;--wp-block-synced-color--rgb:122,0,223;--wp-bound-block-color:var(--wp-block-synced-color);--wp-editor-canvas-background:#ddd;--wp-admin-theme-color:#007cba;--wp-admin-theme-color--rgb:0,124,186;--wp-admin-theme-color-darker-10:#006ba1;--wp-admin-theme-color-darker-10--rgb:0,107,160.5;--wp-admin-theme-color-darker-20:#005a87;--wp-admin-theme-color-darker-20--rgb:0,90,135;--wp-admin-border-width-focus:2px}@media (min-resolution:192dpi){:root{--wp-admin-border-width-focus:1.5px}}.wp-element-button{cursor:pointer}:root .has-very-light-gray-background-color{background-color:#eee}:root .has-very-dark-gray-background-color{background-color:#313131}:root .has-very-light-gray-color{color:#eee}:root .has-very-dark-gray-color{color:#313131}:root .has-vivid-green-cyan-to-vivid-cyan-blue-gradient-background{background:linear-gradient(135deg,#00d084,#0693e3)}:root .has-purple-crush-gradient-background{background:linear-gradient(135deg,#34e2e4,#4721fb 50%,#ab1dfe)}:root .has-hazy-dawn-gradient-background{background:linear-gradient(135deg,#faaca8,#dad0ec)}:root .has-subdued-olive-gradient-background{background:linear-gradient(135deg,#fafae1,#67a671)}:root .has-atomic-cream-gradient-background{background:linear-gradient(135deg,#fdd79a,#004a59)}:root .has-nightshade-gradient-background{background:linear-gradient(135deg,#330968,#31cdcf)}:root .has-midnight-gradient-background{background:linear-gradient(135deg,#020381,#2874fc)}:root{--wp--preset--font-size--normal:16px;--wp--preset--font-size--huge:42px}.has-regular-font-size{font-size:1em}.has-larger-font-size{font-size:2.625em}.has-normal-font-size{font-size:var(--wp--preset--font-size--normal)}.has-huge-font-size{font-size:var(--wp--preset--font-size--huge)}:root .has-text-align-center{text-align:center}:root .has-text-align-left{text-align:left}:root .has-text-align-right{text-align:right}.has-fit-text{white-space:nowrap!important}#end-resizable-editor-section{display:none}.aligncenter{clear:both}.items-justified-left{justify-content:flex-start}.items-justified-center{justify-content:center}.items-justified-right{justify-content:flex-end}.items-justified-space-between{justify-content:space-between}.screen-reader-text{word-wrap:normal!important;border:0;clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px}.screen-reader-text:focus{background-color:#ddd;clip-path:none;color:#444;display:block;font-size:1em;height:auto;left:5px;line-height:normal;padding:15px 23px 14px;text-decoration:none;top:5px;width:auto;z-index:100000}html :where(.has-border-color){border-style:solid}html :where([style*=border-color]){border-style:solid}html :where([style*=border-top-color]){border-top-style:solid}html :where([style*=border-right-color]){border-right-style:solid}html :where([style*=border-bottom-color]){border-bottom-style:solid}html :where([style*=border-left-color]){border-left-style:solid}html :where([style*=border-width]){border-style:solid}html :where([style*=border-top-width]){border-top-style:solid}html :where([style*=border-right-width]){border-right-style:solid}html :where([style*=border-bottom-width]){border-bottom-style:solid}html :where([style*=border-left-width]){border-left-style:solid}html :where(img[class*=wp-image-]){height:auto;max-width:100%}:where(figure){margin:0 0 1em}html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:var(--wp-admin--admin-bar--height,0px)}@media screen and (max-width:600px){html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:0px}}

/*# sourceURL=/wp-includes/css/dist/block-library/common.min.css */
  </style>
  <style id="wp-block-heading-inline-css">
   h1:where(.wp-block-heading).has-background,h2:where(.wp-block-heading).has-background,h3:where(.wp-block-heading).has-background,h4:where(.wp-block-heading).has-background,h5:where(.wp-block-heading).has-background,h6:where(.wp-block-heading).has-background{padding:1.25em 2.375em}h1.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h1.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h2.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h2.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h3.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h3.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h4.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h4.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h5.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h5.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h6.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h6.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]){rotate:180deg}
/*# sourceURL=https://editorial.rottentomatoes.com/wp-includes/blocks/heading/style.min.css */
  </style>
  <style id="wp-block-image-inline-css">

In [5]:
name_year_scores = soup.find_all('div', attrs={'class':'meta-data-wrapper'})
name_year_scores

[<div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/leave_no_trace">Leave No Trace</a>
 <span class="meta-year">(2018)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> <em>Leave No Trace</em> takes an effectively low-key approach to a potentially sensationalistic story -- and further benefits from brilliant work by Ben Foster and Thomasin McKenzie.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> A father and daughter live a perfect but mysterious existence in Forest Park, a beautiful nature reserve near Portland, Ore., rarely making contact with the...											<a class="full-synopsis" data-pageheader="" href="https://www.rottentomatoes.com/m/leave_no_trace" target="_top">View Full Synopsis</a>
 </p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/ben_foster">Ben Foster</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/thomasin_mckenzie">Thomasin McKenzie</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/jeff_kober">Jeff Kober</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/dale-dickey">Dale Dickey</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/debra_granik">Debra Granik</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/toy_story_2">Toy Story 2</a>
 <span class="meta-year">(1999)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> The rare sequel that arguably improves on its predecessor, <em>Toy Story 2</em> uses inventive storytelling, gorgeous animation, and a talented cast to deliver another rich moviegoing experience for all ages.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> Woody (Tom Hanks) is stolen from his home by toy dealer Al McWhiggin (Wayne Knight), leaving Buzz Lightyear (Tim Allen) and the rest of the...											<a class="full-synopsis" data-pageheader="" href="https://www.rottentomatoes.com/m/toy_story_2" target="_top">View Full Synopsis</a>
 </p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/tom_hanks">Tom Hanks</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/tim_allen">Tim Allen</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/joan_cusack">Joan Cusack</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/kelseygrammar">Kelsey Grammer</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/ash-brannon">Ash Brannon</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/john_lasseter">John Lasseter</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/lee_unkrich">Lee Unkrich</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/all_we_imagine_as_light">All We Imagine as Light</a>
 <span class="meta-year">(2024)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> Capturing the here and now of modern India with the spontaneity of a candid photograph, <em>All We Imagine as Light</em> is a lustrous achievement that announces Payal Kapadia as an essential filmmaker.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> The light, the lives, and the textures of contemporary, working-class Mumbai are explored and celebrated by writer/director Payal Kapadia, who won the Grand Prize at...											<a class="full-synopsis" data-pageheader="" href="https://www.rottentomatoes.com/m/all_we_imagine_as_light" target="_top">View Full Synopsis</a>
 </p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/kani_kusruti">Kani Kusruti</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/divya_prabha">Divya Prabha</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/chhaya_kadam">Chhaya Kadam</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/hridhu_haroon">Hridhu Haroon</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/payal_kapadia">Payal Kapadia</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/wallace_and_gromit_vengeance_most_fowl">Wallace &amp; Gromit: Vengeance Most Fowl</a>
 <span class="meta-year">(2024)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> Comforting as cheese and crackers, with some gentle ribbing of modern technology sprinkled on top, <em>Vengeance Most Fowl</em> revives this lovable pair with all their charm intact.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> Aardman's four-time Academy Award®-winning director Nick Park and Emmy Award-nominated Merlin Crossingham return with a brand new epic adventure, Wallace &amp; Gromit: Vengeance Most Fowl....											<a class="full-synopsis" data-pageheader="" href="https://www.rottentomatoes.com/m/wallace_and_gromit_vengeance_most_fowl" target="_top">View Full Synopsis</a>
 </p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/ben_whitehead">Ben Whitehead</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/peter-kay">Peter Kay</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/lauren_patel">Lauren Patel</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/reece_shearsmith">Reece Shearsmith</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/merlin_crossingham">Merlin Crossingham</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/nick_park">Nick Park</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/gloria_2012">Gloria</a>
 <span class="meta-year">(2013)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> Marvelously directed by Sebastian Lelio and beautifully led by a powerful performance from Paulina Garcia, <em>Gloria</em> takes an honest, sweetly poignant look at a type of character that's all too often neglected in Hollywood.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> An aging divorcee (Paulina García) embarks on an intense affair with a man (Sergio Hernández) she picked up at a disco.									</p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/paulina_garcia">Paulina García</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/sergio_hernandez_4">Sergio Hernández</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/diego_fontecilla">Diego Fontecilla</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/coca_guazzini">Coca Guazzini</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/sebastian_lelio">Sebastián Lelio</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/his_house">His House</a>
 <span class="meta-year">(2020)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> Featuring genuine scares through every corridor, <em>His House</em> is a terrifying look at the specters of the refugee experience and a stunning feature debut for Remi Weekes.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> A refugee couple makes a harrowing escape from war-torn South Sudan, but then they struggle to adjust to their new life in an English town...											<a class="full-synopsis" data-pageheader="" href="https://www.rottentomatoes.com/m/his_house" target="_top">View Full Synopsis</a>
 </p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/wunmi_mosaku">Wunmi Mosaku</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/sope_dirisu">Sope Dirisu</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/matt_smith_4">Matt Smith</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/cornell_john">Cornell John</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/remi_weekes">Remi Weekes</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/philadelphia_story">The Philadelphia Story</a>
 <span class="meta-year">(1940)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> Offering a wonderfully witty script, spotless direction from George Cukor, and typically excellent lead performances, <em>The Philadelphia Story</em> is an unqualified classic.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> This classic romantic comedy focuses on Tracy Lord (Katharine Hepburn), a Philadelphia socialite who has split from her husband, C.K. Dexter Haven (Cary Grant), due...											<a class="full-synopsis" data-pageheader="" href="https://www.rottentomatoes.com/m/philadelphia_story" target="_top">View Full Synopsis</a>
 </p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/cary_grant">Cary Grant</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/katharine_hepburn">Katharine Hepburn</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/james_stewart_2">James Stewart</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/ruth_hussey">Ruth Hussey</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/george_cukor">George Cukor</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/seven_samurai_1956">Seven Samurai</a>
 <span class="meta-year">(1954)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> Arguably Akira Kurosawa's masterpiece, The Seven Samurai is an epic adventure classic with an engrossing story, memorable characters, and stunning action sequences that make it one of the most influential films ever made.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six...											<a class="full-synopsis" data-pageheader="" href="https://www.rottentomatoes.com/m/seven_samurai_1956" target="_top">View Full Synopsis</a>
 </p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/toshiro_mifune">Toshiro Mifune</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/takashi_shimura">Takashi Shimura</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/yoshio_inaba">Yoshio Inaba</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/seiji-miyaguchi">Seiji Miyaguchi</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/akirakurosawa">Akira Kurosawa</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/summer_1993">Summer 1993</a>
 <span class="meta-year">(2017)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> <em>Summer 1993 (Estiu 1993)</em> finds writer-director Carla Simón drawing on personal memories to create a thoughtful drama elevated by outstanding work from its young leads.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> Six-year-old Frida looks on in silence as the last objects from her recently deceased mother's apartment in Barcelona are placed in boxes. Although her aunt,...											<a class="full-synopsis" data-pageheader="" href="https://www.rottentomatoes.com/m/summer_1993" target="_top">View Full Synopsis</a>
 </p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/laia_artigas">Laia Artigas</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/paula_robles">Paula Robles</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/bruna_cusi">Bruna Cusí</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/david_verdaguer">David Verdaguer</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/carla_simon">Carla Simón</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/the_tale_of_the_princess_kaguya">The Tale of the Princess Kaguya</a>
 <span class="meta-year">(2013)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> Boasting narrative depth, frank honesty, and exquisite visual beauty, <em>The Tale of the Princess Kaguya</em> is a modern animated treasure with timeless appeal.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> A tiny nymph found inside a bamboo stalk grows into a beautiful and desirable young woman, who orders her suitors to prove their love by...											<a class="full-synopsis" data-pageheader="" href="https://www.rottentomatoes.com/m/the_tale_of_the_princess_kaguya" target="_top">View Full Synopsis</a>
 </p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/chloe_grace_moretz">Chloë Grace Moretz</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/james_caan_3">James Caan</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/mary_steenburgen">Mary Steenburgen</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/darren_criss">Darren Criss</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/isao_takahata">Isao Takahata</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/one_cut_of_the_dead">One Cut of the Dead</a>
 <span class="meta-year">(2017)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> Brainy and bloody in equal measure, <em>One Cut of the Dead</em> reanimates the moribund zombie genre with a refreshing blend of formal daring and clever satire.				</p>
 <p class="meta-detail">
 <span class="title">Synopsis:</span> Real zombies attack a hack director and a film crew who are shooting a low budget zombie film in an abandoned WWII Japanese facility.									</p>
 <p class="meta-detail">
 <span class="title">
 		Starring:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/takayuki_hamatsu">Takayuki Hamatsu</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/yuzuki_akiyama">Yuzuki Akiyama</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/harumi_shuhama">Harumi Shuhama</a>, 				<a class="" href="//www.rottentomatoes.com/celebrity/kazuaki_nagaya">Kazuaki Nagaya</a> </p>
 <p class="meta-detail">
 <span class="title">
 		Directed By:	</span>
 <a class="" href="//www.rottentomatoes.com/celebrity/shinichiro_ueda_2">Shinichiro Ueda</a> </p>
 </div>
 </div>,
 <div class="meta-data-wrapper">
 <div class="meta-title-wrapper">
 <a class="meta-title" href="https://www.rottentomatoes.com/m/toy_story">Toy Story</a>
 <span class="meta-year">(1995)</span>
 </div>
 <div class="meta-scores-wrapper">
 <img alt="Tomatometer icon" decoding="async" src="https://images.fandango.com/cms/assets/c6672520-d359-11ea-a15f-bdf29fa24277--certified-fresh.png"/>
 <span class="tMeterScore">100%</span>
 </div>
 <div class="meta-details-wrapper">
 <p class="meta-detail">
 <span class="title">Critics Consensus:</span> Entertaining as it is innovative, <em>Toy Story</em> reinvigorated animation while heralding the arrival of Pixar as a family-friendly force to be reckoned with.				</p>
 <p class="meta-detail">

### Names

In [7]:
names = [i.find('a').get_text() for i in name_year_scores]
names

['Leave No Trace',
 'Toy Story 2',
 'All We Imagine as Light',
 'Wallace & Gromit: Vengeance Most Fowl',
 'Gloria',
 'His House',
 'The Philadelphia Story',
 'Seven Samurai',
 'Summer 1993',
 'The Tale of the Princess Kaguya',
 'One Cut of the Dead',
 'Toy Story',
 "Singin' in the Rain",
 'Hive',
 'Poetry',
 'Laura',
 'Still Walking',
 'Pinocchio',
 'Nowhere Special',
 'M',
 'Playground',
 'Three Colors: Red',
 'Only Yesterday',
 'Slalom',
 '12 Angry Men',
 'The Black Pirate',
 'Girls Will Be Girls',
 'Tampopo',
 'Cool Hand Luke',
 'The Treasure of the Sierra Madre',
 'Shadow of a Doubt',
 'Anatomy of a Murder',
 'Chained for Life',
 'Tokyo Story',
 'The Wages of Fear',
 'The Grapes of Wrath',
 'The Adventures of Robin Hood',
 'Kind Hearts and Coronets',
 'Battleship Potemkin',
 'Before Sunrise',
 'The Kid',
 'The Age of Shadows',
 'Stagecoach',
 'Rome, Open City',
 'On Becoming a Guinea Fowl',
 'Fanny and Alexander',
 'Ilo Ilo',
 'The Velvet Queen',
 'Grave of the Fireflies',
 'Fireworks Wednesday',
 'Nights of Cabiria',
 'Au Hasard Balthazar',
 'The First Slam Dunk',
 'Mickey and the Bear',
 'Maedchen in Uniform',
 'Stalker',
 'A Man Escaped',
 "Sullivan's Travels",
 'Paper Spiders',
 'Top Hat',
 'Ali: Fear Eats the Soul',
 'Sugar Cane Alley',
 'Local Hero',
 'Bait',
 'Temple Grandin']

### Years

In [10]:
years = [i.find('span', attrs={'class':'meta-year'}).get_text().strip('()') for i in name_year_scores]
years

['2018',
 '1999',
 '2024',
 '2024',
 '2013',
 '2020',
 '1940',
 '1954',
 '2017',
 '2013',
 '2017',
 '1995',
 '1952',
 '2021',
 '2010',
 '1944',
 '2008',
 '1940',
 '2020',
 '1931',
 '2021',
 '1994',
 '1991',
 '2020',
 '1957',
 '1926',
 '2024',
 '1985',
 '1967',
 '1948',
 '1943',
 '1959',
 '2018',
 '1953',
 '1953',
 '1940',
 '1938',
 '1949',
 '1925',
 '1995',
 '1921',
 '2016',
 '1939',
 '1945',
 '2024',
 '1982',
 '2013',
 '2021',
 '1988',
 '2006',
 '1957',
 '1966',
 '2022',
 '2019',
 '1931',
 '1979',
 '1956',
 '1941',
 '2021',
 '1935',
 '1974',
 '1983',
 '1983',
 '2019',
 '2010']

### Scores

In [11]:
scores = [i.find('span', attrs={'class': 'tMeterScore'}).get_text() for i in name_year_scores]
scores

['100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '- -',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%',
 '100%']

### Ranks

In [12]:
ranks = [i.get_text().strip('#') for i in soup.find_all('span', attrs={'class': 'indicator'})]
ranks

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65']

### 2. Store the extracted data in a Pandas DataFrame.

In [18]:
cartoons = pd.DataFrame({'MovieName': names, 'ReleaseYear': years, 'TomatometerScore': scores, 'Rank': ranks})

cartoons

                                MovieName ReleaseYear TomatometerScore Rank
0                          Leave No Trace        2018             100%    1
1                             Toy Story 2        1999             100%    2
2                 All We Imagine as Light        2024             100%    3
3   Wallace & Gromit: Vengeance Most Fowl        2024             100%    4
4                                  Gloria        2013             100%    5
..                                    ...         ...              ...  ...
60                Ali: Fear Eats the Soul        1974             100%   61
61                       Sugar Cane Alley        1983             100%   62
62                             Local Hero        1983             100%   63
63                                   Bait        2019             100%   64
64                         Temple Grandin        2010             100%   65

[65 rows x 4 columns]

### 3. Create a SQLite database named 'Cartoon.db'.

### 4. Save the DataFrame into a table named 'Cartoons'.

In [19]:
import sqlite3

with sqlite3.connect('Cartoon.db') as conn:
    cartoons.to_sql('Cartoons', conn, if_exists='replace', index=False)

### 5. Verify that the data has been successfully inserted into the database.

In [ ]:
conn = sqlite3.connect("Cartoon.db")

result = pd.read_sql("SELECT * FROM Cartoons", conn)

result

conn.close()

                                MovieName ReleaseYear TomatometerScore Rank
0                          Leave No Trace        2018             100%    1
1                             Toy Story 2        1999             100%    2
2                 All We Imagine as Light        2024             100%    3
3   Wallace & Gromit: Vengeance Most Fowl        2024             100%    4
4                                  Gloria        2013             100%    5
..                                    ...         ...              ...  ...
60                Ali: Fear Eats the Soul        1974             100%   61
61                       Sugar Cane Alley        1983             100%   62
62                             Local Hero        1983             100%   63
63                                   Bait        2019             100%   64
64                         Temple Grandin        2010             100%   65

[65 rows x 4 columns]