## PUZZLE 1

DataFramega yangi ustun qo‘shing:

score >= 70 → "Pass"

aks holda → "Fail"

Keyin:

faqat "Pass" bo‘lganlarni chiqaring

1-usul

In [8]:
# sample dataset
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan", "Husan", "Aziza"],
    "score": [45, 82, 67, 30, 90]
})

status = []

for i in df["score"]:
    if i >= 70:
        status.append("Pass")
    else:
        status.append("Fail")

df["status"] = status
    
df[df["status"] == "Pass"]


# Expected Output:

#     name  score status
# 1   Vali     82   Pass
# 4  Aziza     90   Pass

    name  score status
1   Vali     82   Pass
4  Aziza     90   Pass

2-usul

In [12]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan", "Husan", "Aziza"],
    "score": [45, 82, 67, 30, 90]
})

df["status"] = df["score"].apply(lambda x: "Pass" if x >= 70 else "Fail")

df[df["status"] == "Pass"]

    name  score status
1   Vali     82   Pass
4  Aziza     90   Pass

3-usul

In [11]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Vali", "Hasan", "Husan", "Aziza"],
    "score": [45, 82, 67, 30, 90]
})

df["status"] = "Fail"
df.loc[df["score"] >= 70, "status"] = "Pass"

df[df["status"] == "Pass"]

    name  score status
1   Vali     82   Pass
4  Aziza     90   Pass

## Puzzle 2

Har bir product bo‘yicha:

eng katta sales qaysi oyda bo‘lganini toping

1-usul

In [20]:
# sample dataset

df = pd.DataFrame({
    "product": ["A", "A", "B", "B", "C"],
    "month": ["Jan", "Feb", "Jan", "Feb", "Jan"],
    "sales": [100, 200, 300, 100, 400]
})

df[['product', 'month']].loc[df.groupby("product")["sales"].idxmax()]


# Expected Output:

#     product   month
# 1         A     Feb
# 2         B     Jan
# 4         C     Jan

  product month
1       A   Feb
2       B   Jan
4       C   Jan

2-usul

In [26]:
df = pd.DataFrame({
    "product": ["A", "A", "B", "B", "C"],
    "month": ["Jan", "Feb", "Jan", "Feb", "Jan"],
    "sales": [100, 200, 300, 100, 400]
})

result = df.sort_values("sales", ascending=False).drop_duplicates("product")
result[['product', 'month']]

  product month
4       C   Jan
2       B   Jan
1       A   Feb

## PUZZLE 3

Har bir studentni chiqaring:

score yo‘q bo‘lsa → 0 qilib qo‘ying

In [30]:
# sample dataset

students = pd.DataFrame({
    "id": [1,2,3,4],
    "name": ["Ali", "Vali", "Hasan", "Husan"]
})

scores = pd.DataFrame({
    "id": [1,2,4],
    "score": [80, 90, 70]
})

students.merge(scores, how="left", on="id").fillna(0)

# Expected Output:
#     id   name  score
# 0   1    Ali   80.0
# 1   2   Vali   90.0
# 2   3  Hasan    0.0 
# 3   4  Husan   70.0

   id   name  score
0   1    Ali   80.0
1   2   Vali   90.0
2   3  Hasan    0.0
3   4  Husan   70.0

## PUZZLE 4

Har bir customer uchun total amount hisoblang va

faqat total > 200 bo‘lganlarni chiqaring

In [31]:
orders = pd.DataFrame({
    "order_id": [1,2,3,4],
    "customer": ["Ali", "Vali", "Ali", "Hasan"],
    "amount": [100, 200, 150, 300]
})

result = orders.groupby('customer', as_index=False).agg(TotalAmount = ('amount', 'sum'))

result[result['TotalAmount'] > 200]

# Expected Output:
#     customer  amount
# 0      Ali     250
# 1    Hasan     300

  customer  TotalAmount
0      Ali          250
1    Hasan          300

## PUZZLE 5

Har bir user uchun:

sales o‘sgan yoki kamayganini aniqlang

In [36]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Ali", "Vali", "Vali", "Hasan", "Abror", "Abror"],
    "month": ["Jan", "Feb", "Jan", "Feb", "Jan", "Jan", "Feb"],
    "sales": [100, 300, 200, 100, 400, 250, 250]
})

df["trend"] = "No Data"

df["old_sales"] = df.groupby('name')['sales'].shift()

df.loc[df["sales"] > df["old_sales"], "trend"] = "Increase"
df.loc[df["sales"] < df["old_sales"], "trend"] = "Decrease"
df.loc[df["sales"] == df["old_sales"], "trend"] = "Same"

df[["name", "trend"]].drop_duplicates("name", keep="last")

# Expected Output:
#     name     trend
# 0  Abror      Same
# 1    Ali  Increase
# 2  Hasan   No Data
# 3   Vali  Decrease

    name     trend
1    Ali  Increase
3   Vali  Decrease
4  Hasan   No Data
6  Abror      Same