## Homework - 19 Pandas: Grouping

## Easy Questions

Q1. Category Quantity
Using sales_data.csv, calculate total quantity sold for each category.
Use:
groupby()
Display:
•	Category
•	TotalQuantity

In [6]:
import pandas as pd

sales_data = pd.read_csv('data/sales_data.csv')

result = sales_data.groupby('Category')['Quantity'].sum().rename('TotalQuantity')

result

Category
Clothing       157
Electronics    183
Home           144
Name: TotalQuantity, dtype: int64

Q2. Gender Average Salary
Using the population table from population.db, calculate average salary for each gender.
Display:
•	gender
•	AverageSalary

In [16]:
import sqlite3
import pandas as pd

# Database bilan ulanish
conn = sqlite3.connect('data/population.db')

# population.db jadvalini DataFramega yuklash

population = pd.read_sql_query("SELECT * FROM population", conn)

# Gender bo'yicha o'rtacha salary

result = population.groupby('gender', as_index=False).agg(AverageSalary=('salary', 'mean'))

result

conn.close()

   gender  AverageSalary
0  Female  990976.310380
1    Male  994320.475413

Q3. Customer Order Counts
Using customer_orders.csv, count how many orders each customer made.
Display:
•	CustomerID
•	OrderCount
Hint:
Use count() on OrderID.

In [24]:
data = pd.read_csv('data/customer_orders.csv')

result = data.groupby('CustomerID', as_index=False).agg(OrderCount=('OrderID', 'count'))

result

   CustomerID  OrderCount
0         101          21
1         102          21
2         103          20
3         104          20
4         105          18

Q4. State Population Count
Using the population table, count how many records exist for each state.
Display:
•	state
•	RecordCount
Sort by RecordCount in descending order.

In [ ]:
conn = sqlite3.connect('data/population.db')

population = pd.read_sql_query("SELECT * FROM population", conn)

result = (
    population.groupby('state', as_index=False)
        .agg(RecordCount=('state', 'count'))
        .sort_values(by='RecordCount', ascending=False)
    )

result

conn.close()

                   state  RecordCount
4             California         1332
43                 Texas         1293
9                Florida          924
32              New York          674
35                  Ohio          443
46              Virginia          374
8   District of Columbia          370
38          Pennsylvania          350
10               Georgia          326
13              Illinois          296
5               Colorado          287
33        North Carolina          264
42             Tennessee          258
2                Arizona          253
25              Missouri          247
0                Alabama          246
23             Minnesota          240
14               Indiana          226
47            Washington          216
22              Michigan          209
18             Louisiana          194
6            Connecticut          182
36              Oklahoma          178
28                Nevada          172
21         Massachusetts          165
17              Kentucky          161
16                Kansas          145
20              Maryland          143
40        South Carolina          141
15                  Iowa          138
49             Wisconsin          134
44                  Utah          120
30            New Jersey          112
48         West Virginia          104
37                Oregon           96
27              Nebraska           91
31            New Mexico           72
11                Hawaii           62
24           Mississippi           61
3               Arkansas           60
12                 Idaho           60
1                 Alaska           54
7               Delaware           35
41          South Dakota           31
34          North Dakota           27
26               Montana           27
29         New Hampshire           17
39          Rhode Island           17
19                 Maine           10
45               Vermont            9
50               Wyoming            5

Q5. Product Maximum Price
Using sales_data.csv, find the maximum price for each product.
Display:
•	Product
•	MaxPrice

In [30]:
result = (
    sales_data.groupby('Product', as_index=False)
    .agg(MaxPrice=('Price', 'max'))
)

result

                   Product  MaxPrice
0               4K Monitor       350
1             Air Purifier        90
2                 Backpack        40
3             Bedside Lamp        20
4                  Blender        60
5           Blu-ray Player        70
6        Bluetooth Headset        50
7                Bookshelf        80
8              Cargo Pants        30
9             Casual Shoes        30
10            Coffee Maker        50
11            Coffee Table       100
12           Comforter Set        45
13            Cookware Set        60
14            Denim Jacket        45
15             Denim Skirt        25
16              Desk Chair        75
17               Desk Lamp        25
18             Dress Shirt        25
19                   Drone       300
20     External Hard Drive        80
21         Fitness Tracker        60
22            Formal Shirt        35
23          Gaming Console       400
24              Headphones       150
25                  Hoodie        25
26                   Jeans        30
27           Kitchen Scale        20
28                  Laptop       800
29  Point-and-Shoot Camera       250
30         Pressure Cooker        50
31               Projector       200
32                Smart TV      1000
33              Smartphone       400
34                Sneakers        50
35                Soundbar       150
36             Sport Shoes        40
37              Steam Iron        30
38            Summer Dress        30
39              Sunglasses        15
40                 Sweater        35
41              Sweatpants        20
42              Sweatshirt        35
43                 T-Shirt        20
44                  Tablet       300
45                 Toaster        25
46          Vacuum Cleaner        80
47        Wireless Earbuds       120
48          Wireless Mouse        25
49        Wireless Speaker        70

Q6. Customer Total Quantity
Using customer_orders.csv, calculate total quantity purchased by each customer.
Display:
-	CustomerID
-	TotalQuantity

In [31]:
result = (
    data.groupby('CustomerID', as_index=False)
    .agg(TotalQuantity=('Quantity', 'sum'))
)

result

   CustomerID  TotalQuantity
0         101             27
1         102             25
2         103             28
3         104             27
4         105             21

Q7. Daily Transactions
Using sales_data.csv, count the number of transactions per day.
Steps:
1.	Convert Date column to datetime.
2.	Extract only the date part if needed.
3.	Group by date.
4.	Count transactions.
Display:
-	Date
-	TransactionCount

In [32]:
# Date ustunini datetime formatiga o'tkazish
sales_data['Date'] = pd.to_datetime(sales_data['Date'])

# Faqat sana qismini olish
sales_data['Date'] = sales_data['Date'].dt.date

# Har bir sana bo'yicha tranzaksiyalar sonini hisoblash
result = (
    sales_data
    .groupby('Date', as_index=False)
    .size()
    .rename(columns={'size': 'TransactionCount'})
)

result

          Date  TransactionCount
0   2023-01-01                 2
1   2023-01-02                 2
2   2023-01-03                 2
3   2023-01-04                 2
4   2023-01-05                 2
5   2023-01-06                 2
6   2023-01-07                 2
7   2023-01-08                 2
8   2023-01-09                 2
9   2023-01-10                 2
10  2023-01-11                 2
11  2023-01-12                 2
12  2023-01-13                 2
13  2023-01-14                 2
14  2023-01-15                 2
15  2023-01-16                 2
16  2023-01-17                 2
17  2023-01-18                 2
18  2023-01-19                 2
19  2023-01-20                 2
20  2023-01-21                 2
21  2023-01-22                 2
22  2023-01-23                 2
23  2023-01-24                 2
24  2023-01-25                 2

Q8. Gender Distribution
Using the population table, count the total number of records for each gender.
Display:
-	gender
-	Count

In [ ]:
conn = sqlite3.connect('data/population.db')

population = pd.read_sql_query("SELECT * FROM population", conn)

result = (
    population.groupby('gender', as_index=False)
    ['gender'].count()
)

result

conn.close()

   gender
0    5896
1    5755

Q9. Category Minimum Price
Using sales_data.csv, find the minimum price for each category.
Display:
-	Category
-	MinPrice

In [36]:
result = (
    sales_data.groupby('Category', as_index=False)
    .agg(MinPrice=('Price', 'min'))
)

result

      Category  MinPrice
0     Clothing        15
1  Electronics        25
2         Home        20

Q10. State Payroll
Using the population table, calculate total salary paid in each state.
Display:
-	state
-	TotalSalary

Sort by TotalSalary in descending order.

In [ ]:
conn = sqlite3.connect('data/population.db')

population = pd.read_sql_query("SELECT * FROM population", conn)

result = (
    population.groupby('state', as_index=False)
    .agg(TotalSalary=('salary', 'sum'))
    .sort_values(by='TotalSalary', ascending=False)
)

result

conn.close()

                   state  TotalSalary
4             California   1330653875
43                 Texas   1286316084
9                Florida    918868303
32              New York    665594037
35                  Ohio    439992889
46              Virginia    372164347
8   District of Columbia    371049623
38          Pennsylvania    351605611
10               Georgia    322022024
13              Illinois    300167507
5               Colorado    295769227
33        North Carolina    273488752
2                Arizona    264307774
25              Missouri    246690864
0                Alabama    239868238
42             Tennessee    238406947
23             Minnesota    230542724
14               Indiana    225552872
22              Michigan    205889561
47            Washington    203776261
18             Louisiana    191807386
6            Connecticut    182791782
36              Oklahoma    174473660
28                Nevada    174043836
17              Kentucky    163426153
21         Massachusetts    157338487
40        South Carolina    145944565
16                Kansas    141800227
15                  Iowa    140033760
20              Maryland    138318134
44                  Utah    125115017
49             Wisconsin    115278555
30            New Jersey    112301287
48         West Virginia    110005209
37                Oregon     88692872
27              Nebraska     88112165
3               Arkansas     67802109
31            New Mexico     66781902
11                Hawaii     59823980
12                 Idaho     58171192
24           Mississippi     54472990
1                 Alaska     54236152
41          South Dakota     36569025
7               Delaware     32273073
34          North Dakota     25450969
26               Montana     22974843
39          Rhode Island     19360083
29         New Hampshire     13450782
19                 Maine      9672603
45               Vermont      7018613
50               Wyoming      4841731

### Medium Questions

Q11. Multi-Level Sales Grouping
Using sales_data.csv, group data by Date and Category.
Calculate total quantity sold for each date-category pair.
Steps:
1.	Convert Date to datetime.
2.	Group by Date and Category.
3.	Calculate total Quantity.
Display:
-	Date
-	Category
-	TotalQuantity

In [46]:
sales_data['Date'] = pd.to_datetime(sales_data['Date'])

result = (
    sales_data.groupby(['Date', 'Category'], as_index=False)
    .agg(TotalQuantity=('Quantity', 'sum'))
)

result

         Date     Category  TotalQuantity
0  2023-01-01     Clothing              5
1  2023-01-01  Electronics             10
2  2023-01-02  Electronics              8
3  2023-01-02         Home             12
4  2023-01-03     Clothing             15
5  2023-01-03         Home              6
6  2023-01-04     Clothing              7
7  2023-01-04  Electronics             10
8  2023-01-05  Electronics             12
9  2023-01-05         Home              8
10 2023-01-06     Clothing             10
11 2023-01-06         Home              5
12 2023-01-07     Clothing              6
13 2023-01-07  Electronics             15
14 2023-01-08  Electronics             11
15 2023-01-08         Home              9
16 2023-01-09     Clothing             13
17 2023-01-09         Home              7
18 2023-01-10     Clothing              8
19 2023-01-10  Electronics             14
20 2023-01-11  Electronics              9
21 2023-01-11         Home             10
22 2023-01-12     Clothing             11
23 2023-01-12         Home              6
24 2023-01-13     Clothing              7
25 2023-01-13  Electronics             12
26 2023-01-14  Electronics             10
27 2023-01-14         Home              8
28 2023-01-15     Clothing             14
29 2023-01-15         Home              7
30 2023-01-16     Clothing              6
31 2023-01-16  Electronics              9
32 2023-01-17  Electronics             13
33 2023-01-17         Home             12
34 2023-01-18     Clothing              8
35 2023-01-18         Home             11
36 2023-01-19     Clothing              7
37 2023-01-19  Electronics             15
38 2023-01-20  Electronics              8
39 2023-01-20         Home             10
40 2023-01-21     Clothing             12
41 2023-01-21         Home              6
42 2023-01-22     Clothing              9
43 2023-01-22  Electronics             11
44 2023-01-23  Electronics              7
45 2023-01-23         Home             14
46 2023-01-24     Clothing              8
47 2023-01-24         Home             13
48 2023-01-25     Clothing             11
49 2023-01-25  Electronics              9

Q12. Custom Aggregation by State
Using the population table, group data by state.
For the salary column, calculate:
-	minimum salary
-	maximum salary
-	average salary
-	total salary

Use:
.agg()

Display:
-	state
-	MinSalary
-	MaxSalary
-	AvgSalary
-	TotalSalary

In [ ]:
conn = sqlite3.connect('data/population.db')

population = pd.read_sql_query("SELECT * FROM population", conn)

result = (
    population.groupby('state', as_index=False)
    .agg
    (
        MinSalary=('salary', 'min'),
        MaxSalary=('salary', 'max'),
        AvgSalary=('salary', 'mean'),
        TotalSalary=('salary', 'sum')
    )
)

result

conn.close()

                   state  MinSalary  MaxSalary     AvgSalary  TotalSalary
0                Alabama      18515    1998323  9.750741e+05    239868238
1                 Alaska       3678    1984665  1.004373e+06     54236152
2                Arizona       7303    1988034  1.044695e+06    264307774
3               Arkansas      19945    1992899  1.130035e+06     67802109
4             California       1899    1998944  9.989894e+05   1330653875
5               Colorado       1192    1999129  1.030555e+06    295769227
6            Connecticut       1263    1993114  1.004350e+06    182791782
7               Delaware      67517    1897296  9.220878e+05     32273073
8   District of Columbia       2344    1997136  1.002837e+06    371049623
9                Florida       2184    1998236  9.944462e+05    918868303
10               Georgia       9288    1999095  9.877976e+05    322022024
11                Hawaii      15397    1942831  9.649029e+05     59823980
12                 Idaho       2074    1997765  9.695199e+05     58171192
13              Illinois      16655    1998860  1.014079e+06    300167507
14               Indiana       5170    1997704  9.980216e+05    225552872
15                  Iowa       3184    1991852  1.014737e+06    140033760
16                Kansas       9137    1984617  9.779326e+05    141800227
17              Kentucky       3045    1998173  1.015069e+06    163426153
18             Louisiana       1975    1997675  9.886979e+05    191807386
19                 Maine      26856    1956418  9.672603e+05      9672603
20              Maryland      31298    1980973  9.672597e+05    138318134
21         Massachusetts        553    1988599  9.535666e+05    157338487
22              Michigan       3147    1997998  9.851175e+05    205889561
23             Minnesota       9962    1996528  9.605947e+05    230542724
24           Mississippi      32254    1975503  8.929998e+05     54472990
25              Missouri       2245    1965817  9.987484e+05    246690864
26               Montana       5066    1844963  8.509201e+05     22974843
27              Nebraska       1690    1982375  9.682655e+05     88112165
28                Nevada      21874    1994171  1.011883e+06    174043836
29         New Hampshire      42695    1814893  7.912225e+05     13450782
30            New Jersey       4633    1994424  1.002690e+06    112301287
31            New Mexico       3047    1918470  9.275264e+05     66781902
32              New York       1404    1998712  9.875282e+05    665594037
33        North Carolina       3151    1994781  1.035942e+06    273488752
34          North Dakota      96217    1943911  9.426285e+05     25450969
35                  Ohio      19860    1997533  9.932119e+05    439992889
36              Oklahoma        377    1978204  9.801891e+05    174473660
37                Oregon      12673    1997814  9.238841e+05     88692872
38          Pennsylvania       2722    2000000  1.004587e+06    351605611
39          Rhode Island       7204    1973923  1.138828e+06     19360083
40        South Carolina       8337    1993952  1.035068e+06    145944565
41          South Dakota      51278    1955464  1.179646e+06     36569025
42             Tennessee        230    1971555  9.240579e+05    238406947
43                 Texas        241    1999968  9.948307e+05   1286316084
44                  Utah        656    1976453  1.042625e+06    125115017
45               Vermont      56696    1872090  7.798459e+05      7018613
46              Virginia       2304    1996748  9.950918e+05    372164347
47            Washington      11736    1993675  9.434086e+05    203776261
48         West Virginia      44890    1985185  1.057742e+06    110005209
49             Wisconsin       2267    1993943  8.602877e+05    115278555
50               Wyoming      27728    1367561  9.683462e+05      4841731

Q13. Customer Expenditure
Using customer_orders.csv, create a new column:
Total_Spent = Quantity * Price
Then calculate total spending for each customer.
Display:
-	CustomerID
-	TotalSpent

Sort by TotalSpent in descending order.

In [49]:
data['TotalSpent'] = data['Quantity'] * data['Price']

result = (
    data.groupby('CustomerID', as_index=False)
    ['TotalSpent'].sum()
    .sort_values(by='TotalSpent', ascending=False)
)

result

   CustomerID  TotalSpent
3         104        3955
0         101        3425
1         102        3425
2         103        2590
4         105        1640

Q14. High Salary States
Using the population table:
1.	Calculate average salary for each state.
2.	Filter only states where average salary is greater than 50000.

Display:
-	state
-	AverageSalary

Sort by AverageSalary in descending order.

In [ ]:
conn = sqlite3.connect('data/population.db')

population = pd.read_sql_query("SELECT * FROM population", conn)

result = (
    population.groupby('state', as_index=False)
    .agg(AverageSalary=('salary', 'mean'))
    .sort_values(by='AverageSalary', ascending=False)
)

result[result['AverageSalary'] > 50000]

conn.close()

                   state  AverageSalary
41          South Dakota   1.179646e+06
39          Rhode Island   1.138828e+06
3               Arkansas   1.130035e+06
48         West Virginia   1.057742e+06
2                Arizona   1.044695e+06
44                  Utah   1.042625e+06
33        North Carolina   1.035942e+06
40        South Carolina   1.035068e+06
5               Colorado   1.030555e+06
17              Kentucky   1.015069e+06
15                  Iowa   1.014737e+06
13              Illinois   1.014079e+06
28                Nevada   1.011883e+06
38          Pennsylvania   1.004587e+06
1                 Alaska   1.004373e+06
6            Connecticut   1.004350e+06
8   District of Columbia   1.002837e+06
30            New Jersey   1.002690e+06
4             California   9.989894e+05
25              Missouri   9.987484e+05
14               Indiana   9.980216e+05
46              Virginia   9.950918e+05
43                 Texas   9.948307e+05
9                Florida   9.944462e+05
35                  Ohio   9.932119e+05
18             Louisiana   9.886979e+05
10               Georgia   9.877976e+05
32              New York   9.875282e+05
22              Michigan   9.851175e+05
36              Oklahoma   9.801891e+05
16                Kansas   9.779326e+05
0                Alabama   9.750741e+05
12                 Idaho   9.695199e+05
50               Wyoming   9.683462e+05
27              Nebraska   9.682655e+05
19                 Maine   9.672603e+05
20              Maryland   9.672597e+05
11                Hawaii   9.649029e+05
23             Minnesota   9.605947e+05
21         Massachusetts   9.535666e+05
47            Washington   9.434086e+05
34          North Dakota   9.426285e+05
31            New Mexico   9.275264e+05
42             Tennessee   9.240579e+05
37                Oregon   9.238841e+05
7               Delaware   9.220878e+05
24           Mississippi   8.929998e+05
49             Wisconsin   8.602877e+05
26               Montana   8.509201e+05
29         New Hampshire   7.912225e+05
45               Vermont   7.798459e+05

Q15. Product Popularity
Using customer_orders.csv, calculate total quantity sold for each product.

Display:

-	Product
-	TotalQuantitySold

Sort from highest to lowest.

In [54]:
result = (
    data.groupby('Product', as_index=False)
    .agg(TotalQuantitySold=('Quantity', 'sum'))
    .sort_values(by='TotalQuantitySold', ascending=False)
)

result

                   Product  TotalQuantitySold
5              Cargo Pants                  6
19            Formal Shirt                  6
41        Wireless Earbuds                  6
30              Smartphone                  5
15             Dress Shirt                  5
32             Sport Shoes                  5
35              Sunglasses                  5
0                 Backpack                  4
1                  Blender                  4
8             Coffee Table                  3
9            Comforter Set                  3
6             Casual Shoes                  3
39                 Toaster                  3
36                 Sweater                  3
31                Sneakers                  3
33              Steam Iron                  3
21          Gaming Console                  3
7             Coffee Maker                  3
17     External Hard Drive                  3
18         Fitness Tracker                  3
29                Smart TV                  3
34            Summer Dress                  3
20            Formal Shoes                  3
42          Wireless Mouse                  3
24                   Jeans                  3
2           Blu-ray Player                  2
4                Bookshelf                  2
3        Bluetooth Headset                  2
38                  Tablet                  2
11            Denim Jacket                  2
13              Desk Chair                  2
26                  Laptop                  2
23                  Hoodie                  2
14               Desk Lamp                  2
16                   Drone                  2
27  Point-and-Shoot Camera                  2
43        Wireless Speaker                  2
37              Sweatshirt                  2
40        Wireless Charger                  2
28               Projector                  2
10            Cookware Set                  1
25           Kitchen Scale                  1
12             Denim Skirt                  1
22              Headphones                  1

Q16. Sales Statistics
Using sales_data.csv, calculate price statistics for each category.

For each category, calculate:

-	mean price
-	standard deviation of price
-	minimum price
-	maximum price

Use:
.agg()

Display:

-	Category
-	MeanPrice
-	StdPrice
-	MinPrice
-	MaxPrice

In [60]:
result = (
    sales_data.groupby('Category', as_index=False)
    .agg
    (
        AvgPrice=('Price', 'mean'),
        StdPrice=('Price', 'std'),
        MinPrice=('Price', 'min'),
        MaxPrice=('Price', 'max')
    )
)

result

      Category    AvgPrice    StdPrice  MinPrice  MaxPrice
0     Clothing   31.176471    9.275204        15        50
1  Electronics  276.764706  266.955879        25      1000
2         Home   55.000000   26.076810        20       100

Q17. Gender and State Salary
Using the population table, calculate average salary for each gender inside each state.

Group by:

-	state
-	gender

Display:

-	state
-	gender
-	AverageSalary

Sort by state.

In [ ]:
conn = sqlite3.connect('data/population.db')

population = pd.read_sql_query("SELECT * FROM population", conn)

result = (
    population.groupby(['state', 'gender'], as_index=False)
    .agg(AverageSalary=('salary', 'mean'))
)

result

conn.close()

             state  gender  AverageSalary
0          Alabama  Female   9.439834e+05
1          Alabama    Male   1.014151e+06
2           Alaska  Female   9.448596e+05
3           Alaska    Male   1.063887e+06
4          Arizona  Female   1.019114e+06
..             ...     ...            ...
96   West Virginia  Female   9.905933e+05
97   West Virginia    Male   1.127525e+06
98       Wisconsin  Female   8.399021e+05
99       Wisconsin    Male   8.819278e+05
100        Wyoming  Female   9.683462e+05

[101 rows x 3 columns]

Q18. Daily Revenue
Using sales_data.csv, create a new column:
Revenue = Quantity * Price
Then calculate total revenue per day.
Steps:

1.	Convert Date to datetime.
2.	Create Revenue.
3.	Group by Date.
4.	Calculate total revenue.

Display:

-	Date
-	DailyRevenue

In [64]:
sales_data['Date'] = pd.to_datetime(sales_data['Date'])

sales_data['Revenue'] = sales_data['Quantity'] * sales_data['Price']

result = (
    sales_data.groupby('Date', as_index=False)
    .agg(DailyRevenue=('Revenue', 'sum'))
)

result

         Date  DailyRevenue
0  2023-01-01          8100
1  2023-01-02          3800
2  2023-01-03           810
3  2023-01-04          1745
4  2023-01-05          3800
5  2023-01-06           900
6  2023-01-07         15150
7  2023-01-08          1950
8  2023-01-09          1215
9  2023-01-10          5880
10 2023-01-11          1320
11 2023-01-12           315
12 2023-01-13           980
13 2023-01-14          3800
14 2023-01-15           875
15 2023-01-16           720
16 2023-01-17          2840
17 2023-01-18           530
18 2023-01-19          2495
19 2023-01-20          2200
20 2023-01-21           930
21 2023-01-22           545
22 2023-01-23          1050
23 2023-01-24          1240
24 2023-01-25          3480

Q19. Top Spending Customers
Using customer_orders.csv, calculate total spending for each customer.

Formula:

Total_Spent = Quantity * Price

Find the top 5 customers by total spending.

Display:

-	CustomerID
-	TotalSpent

In [65]:
data['TotalSpent'] = data['Quantity'] * data['Price']

result = (
    data.groupby('CustomerID', as_index=False)
    ['TotalSpent'].sum()
    .sort_values(by='TotalSpent', ascending=False)
)

result.head()

   CustomerID  TotalSpent
3         104        3955
0         101        3425
1         102        3425
2         103        2590
4         105        1640

Q20. Unique Products per Category
Using sales_data.csv, calculate how many unique products exist in each category.

Use:

nunique()

Display:

-	Category
-	UniqueProductCount

Sort by UniqueProductCount in descending order.

In [67]:
result= (
    sales_data.groupby('Category', as_index=False)
    .agg(UniqueProductCount=('Product', 'nunique'))
    .sort_values(by='UniqueProductCount', ascending=False)
)

result

      Category  UniqueProductCount
0     Clothing                  17
1  Electronics                  17
2         Home                  16

### Hard Questions

Q21. Gender Salary Gap Intelligence Report
Using the population table from population.db, create a salary gap report by state and gender.

Your final report should include:

-	state
-	MaleAvgSalary
-	FemaleAvgSalary
-	OverallAvgSalary
-	SalaryGap
-	EqualityIndex
-	InequalityRank

Use these formulas:

SalaryGap = abs(MaleAvgSalary - FemaleAvgSalary)

EqualityIndex = 1 - (SalaryGap / OverallAvgSalary)

Requirements:

1.	Group by state and gender.
2.	Calculate average salary.
3.	Reshape the result using pivot_table() or unstack().
4.	Calculate SalaryGap.
5.	Calculate EqualityIndex.
6.	Rank states by highest salary gap.
7.	Export the final result as:

salary_gap_report.csv

Note:

If the dataset contains gender values other than Male/Female, handle them carefully and explain your approach in a comment.

In [ ]:
conn = sqlite3.connect('data/population.db')

population = pd.read_sql_query("SELECT * FROM population", conn)

# Group by state and gender. Calculate average salary.

result = (
    population.groupby(['state', 'gender'], as_index=False)
    .agg(AverageSalary=('salary', 'mean'))   
)

# Reshape the result using pivot_table() or unstack().

result = result.pivot_table(
    index='state',
    columns='gender',
    values='AverageSalary'
).reset_index()

# rename columns name
result = result.rename(columns={
    'Male': 'MaleAvgSalary',
    'Female': 'FemaleAvgSalary'
})

# Overall average salary
overall_avg = (
    population
    .groupby('state', as_index=False)
    .agg(OverallAvgSalary=('salary', 'mean'))
)

# Add OverallAvgSalary
result = result.merge(overall_avg, on='state')

# Calculate SalaryGap.

result['SalaryGap'] = abs(
    result['MaleAvgSalary'] - result['FemaleAvgSalary']
)

# Calculate EqualityIndex.

result['EqualityIndex'] = (
    1 - result['SalaryGap'] / result['OverallAvgSalary']
).round(4)

# 6.	Rank states by highest salary gap.

result = result.sort_values(by='SalaryGap', ascending=False)

# 7.	Export the final result as: salary_gap_report.csv

result.to_csv('data/salary_gap_report.csv', index=False)

result

conn.close()

,state,FemaleAvgSalary,MaleAvgSalary,OverallAvgSalary,SalaryGap,EqualityIndex
29,New Hampshire,4.918790e+05,9.545007e+05,7.912225e+05,462621.727273,0.4153
45,Vermont,9.249995e+05,6.637230e+05,7.798459e+05,261276.500000,0.6650
44,Utah,9.275456e+05,1.157705e+06,1.042625e+06,230159.150000,0.7793
15,Iowa,9.110479e+05,1.131189e+06,1.014737e+06,220140.728346,0.7831
40,South Carolina,9.494803e+05,1.144123e+06,1.035068e+06,194642.529196,0.8120
31,New Mexico,1.014158e+06,8.307024e+05,9.275264e+05,183455.953560,0.8022
24,Mississippi,9.785611e+05,8.045865e+05,8.929998e+05,173974.563441,0.8052
26,Montana,7.696364e+05,9.068027e+05,8.509201e+05,137166.323864,0.8388
48,West Virginia,9.905933e+05,1.127525e+06,1.057742e+06,136931.443951,0.8705
18,Louisiana,1.052120e+06,9.183821e+05,9.886979e+05,133737.812873,0.8647
3,Arkansas,1.071826e+06,1.196560e+06,1.130035e+06,124733.892857,0.8896
1,Alaska,9.448596e+05,1.063887e+06,1.004373e+06,119027.111111,0.8815
5,Colorado,9.786821e+05,1.091466e+06,1.030555e+06,112783.855523,0.8906
11,Hawaii,9.145610e+05,1.022189e+06,9.649029e+05,107627.517241,0.8885
25,Missouri,9.501275e+05,1.052772e+06,9.987484e+05,102644.119658,0.8972
28,Nevada,9.648363e+05,1.060036e+06,1.011883e+06,95199.819878,0.9059
14,Indiana,9.606615e+05,1.045095e+06,9.980216e+05,84433.747937,0.9154
7,Delaware,9.743381e+05,8.912126e+05,9.220878e+05,83125.440559,0.9099
37,Oregon,9.644219e+05,8.833463e+05,9.238841e+05,81075.625000,0.9122
36,Oklahoma,1.020988e+06,9.453403e+05,9.801891e+05,75647.438262,0.9228
41,South Dakota,1.152431e+06,1.222736e+06,1.179646e+06,70305.605263,0.9404
0,Alabama,9.439834e+05,1.014151e+06,9.750741e+05,70168.101252,0.9280
30,New Jersey,9.730908e+05,1.040746e+06,1.002690e+06,67655.362812,0.9325
39,Rhode Island,1.115347e+06,1.181877e+06,1.138828e+06,66530.151515,0.9416
34,North Dakota,8.973920e+05,9.616754e+05,9.426285e+05,64283.421053,0.9318
9,Florida,1.024820e+06,9.620336e+05,9.944462e+05,62786.654665,0.9369
47,Washington,9.750885e+05,9.155854e+05,9.434086e+05,59503.114851,0.9369
2,Arizona,1.019114e+06,1.078490e+06,1.044695e+06,59376.683486,0.9432
6,Connecticut,1.034221e+06,9.787473e+05,1.004350e+06,55473.435374,0.9448
27,Nebraska,9.379545e+05,9.920389e+05,9.682655e+05,54084.466176,0.9441
16,Kansas,1.003078e+06,9.544633e+05,9.779326e+05,48614.881905,0.9503
32,New York,1.009189e+06,9.639896e+05,9.875282e+05,45199.502324,0.9542
4,California,1.021096e+06,9.781717e+05,9.989894e+05,42924.425317,0.9570
49,Wisconsin,8.399021e+05,8.819278e+05,8.602877e+05,42025.684950,0.9511
38,Pennsylvania,1.026638e+06,9.862314e+05,1.004587e+06,40406.322269,0.9598
12,Idaho,9.890428e+05,9.524373e+05,9.695199e+05,36605.473214,0.9622
33,North Carolina,1.021237e+06,1.053861e+06,1.035942e+06,32623.869255,0.9685
20,Maryland,9.811548e+05,9.496150e+05,9.672597e+05,31539.777381,0.9674
46,Virginia,9.804599e+05,1.011032e+06,9.950918e+05,30571.847500,0.9693
13,Illinois,9.996439e+05,1.029948e+06,1.014079e+06,30304.243102,0.9701
22,Michigan,9.695024e+05,9.991711e+05,9.851175e+05,29668.714141,0.9699
23,Minnesota,9.516323e+05,9.723148e+05,9.605947e+05,20682.487557,0.9785
42,Tennessee,9.141396e+05,9.320342e+05,9.240579e+05,17894.648161,0.9806
43,Texas,9.897474e+05,9.999534e+05,9.948307e+05,10206.014112,0.9897
19,Maine,9.622990e+05,9.722216e+05,9.672603e+05,9922.600000,0.9897
21,Massachusetts,9.575355e+05,9.496455e+05,9.535666e+05,7889.981781,0.9917
35,Ohio,9.964176e+05,9.901339e+05,9.932119e+05,6283.706191,0.9937
17,Kentucky,1.012420e+06,1.017621e+06,1.015069e+06,5200.975764,0.9949
8,District of Columbia,1.004081e+06,1.001695e+06,1.002837e+06,2385.889143,0.9976
10,Georgia,9.867592e+05,9.887985e+05,9.877976e+05,2039.207831,0.9979
50,Wyoming,9.683462e+05,NaN,9.683462e+05,NaN,NaN

Q22. Revenue Performance Analytics Report
Using sales_data.csv, create a revenue performance report.
First create:
Revenue = Quantity * Price
Your category-level report should include:
•	Category
•	TotalRevenue
•	TotalQuantity
•	AveragePrice
•	ProductCount
•	PerformanceStatus
Rules:
If TotalRevenue >= average category revenue:
    PerformanceStatus = "Above Average"
else:
    PerformanceStatus = "Underperforming"
Also create a product-level report with:
•	Product
•	Category
•	ProductRevenue
•	ProductQuantity
Requirements:
1.	Calculate total revenue by category.
2.	Calculate total quantity by category.
3.	Calculate average price by category.
4.	Count unique products by category.
5.	Identify underperforming categories.
6.	Find top 10 products by revenue.
7.	Export category report as:
category_performance.csv
8.	Export top product report as:
top_products_by_revenue.csv

In [83]:
# Create Revenue column
sales_data['Revenue'] = sales_data['Quantity'] * sales_data['Price']

# Category-level report
category_report = (
    sales_data
    .groupby('Category', as_index=False)
    .agg(
        TotalRevenue=('Revenue', 'sum'),
        TotalQuantity=('Quantity', 'sum'),
        AveragePrice=('Price', 'mean'),
        ProductCount=('Product', 'nunique')
    )
)

# Calculate average category revenue
average_category_revenue = category_report['TotalRevenue'].mean()

# Create PerformanceStatus column
category_report['PerformanceStatus'] = category_report['TotalRevenue'].apply(
    lambda x: 'Above Average'
    if x >= average_category_revenue
    else 'Underperforming'
)

# Product-level report
product_report = (
    sales_data
    .groupby(['Product', 'Category'], as_index=False)
    .agg(
        ProductRevenue=('Revenue', 'sum'),
        ProductQuantity=('Quantity', 'sum')
    )
)

# Find top 10 products by revenue
top_products = (
    product_report
    .sort_values(by='ProductRevenue', ascending=False)
    .head(10)
)

# Export reports
category_report.to_csv(
    'data/category_performance.csv',
    index=False
)

top_products.to_csv(
    'data/top_products_by_revenue.csv',
    index=False
)

# Display results
print(category_report)
print(top_products)

      Category  TotalRevenue  TotalQuantity  AveragePrice  ProductCount  \
0     Clothing          5080            157     31.176471            17
1  Electronics         53945            183    276.764706            17
2         Home          7645            144     55.000000            16

  PerformanceStatus
0   Underperforming
1     Above Average
2   Underperforming
                   Product     Category  ProductRevenue  ProductQuantity
32                Smart TV  Electronics           15000               15
28                  Laptop  Electronics            8000               10
23          Gaming Console  Electronics            5600               14
44                  Tablet  Electronics            3600               12
33              Smartphone  Electronics            3200                8
0               4K Monitor  Electronics            3150                9
19                   Drone  Electronics            3000               10
31               Projector  Electronics            2600               13
35                Soundbar  Electronics            2250               15
29  Point-and-Shoot Camera  Electronics            2000                8

Q23. Customer Behavior Segmentation Engine
Using customer_orders.csv, create a customer segmentation report.
First create:
Total_Spent = Quantity * Price
Your final report should include:
•	CustomerID
•	TotalSpent
•	TotalOrders
•	TotalQuantity
•	UniqueProductTypes
•	CustomerSegment
•	IsRepeatBuyer
Rules:
If customer purchased more than 5 unique product types:
    IsRepeatBuyer = True
else:
    IsRepeatBuyer = False
Use spending quantiles for segmentation:
Top 25% spending customers = VIP
Middle 50% spending customers = Regular
Bottom 25% spending customers = Low Spender
Requirements:
1.	Group by CustomerID.
2.	Calculate total spending.
3.	Count total orders.
4.	Calculate total quantity.
5.	Count unique product types.
6.	Segment customers using quantiles.
7.	Identify repeat buyers.
8.	Export final result as:
customer_segments.csv

2 Next Topic Questions: Combining Objects
These questions are for pre-study.
Main focus is to understand the basic idea of combining DataFrames.

In [84]:
import pandas as pd

# Load dataset
customer_orders = pd.read_csv('data/customer_orders.csv')

# Create Total_Spent column
customer_orders['Total_Spent'] = (
    customer_orders['Quantity'] * customer_orders['Price']
)

# Customer-level report
customer_report = (
    customer_orders
    .groupby('CustomerID', as_index=False)
    .agg(
        TotalSpent=('Total_Spent', 'sum'),
        TotalOrders=('CustomerID', 'count'),
        TotalQuantity=('Quantity', 'sum'),
        UniqueProductTypes=('Product', 'nunique')
    )
)

# Spending quantiles
q1 = customer_report['TotalSpent'].quantile(0.25)
q3 = customer_report['TotalSpent'].quantile(0.75)

# Customer segmentation
customer_report['CustomerSegment'] = customer_report['TotalSpent'].apply(
    lambda x: (
        'VIP'
        if x >= q3
        else 'Regular'
        if x >= q1
        else 'Low Spender'
    )
)

# Repeat buyer flag
customer_report['IsRepeatBuyer'] = (
    customer_report['UniqueProductTypes'] > 5
)

# Export report
customer_report.to_csv(
    'data/customer_segments.csv',
    index=False
)

# Display result
print(customer_report)

   CustomerID  TotalSpent  TotalOrders  TotalQuantity  UniqueProductTypes  \
0         101        3425           21             27                  17
1         102        3425           21             25                  17
2         103        2590           20             28                  16
3         104        3955           20             27                  17
4         105        1640           18             21                  14

  CustomerSegment  IsRepeatBuyer
0             VIP           True
1             VIP           True
2         Regular           True
3             VIP           True
4     Low Spender           True

### 2 Next Topic Questions: Combining Objects These questions are for pre-study. Main focus is to understand the basic idea of combining DataFrames.

Q24. merge() Introduction
Take the first 5 rows from customer_orders.csv.
Create a new small DataFrame manually:
CustomerID, CustomerName, City
Make sure some CustomerID values match the customer_orders.csv data.
Then merge both DataFrames using:
pd.merge()
Merge key:
CustomerID
Display:
•	OrderID
•	CustomerID
•	CustomerName
•	City
•	Product
•	Quantity

In [85]:
import pandas as pd

# Load dataset
customer_orders = pd.read_csv('data/customer_orders.csv')

# Take first 5 rows
orders = customer_orders.head(5)

# Create a small DataFrame manually
customers = pd.DataFrame({
    'CustomerID': [101, 102, 103, 104, 105],   # Use IDs that exist in your dataset
    'CustomerName': ['Ali', 'Vali', 'Hasan', 'Husan', 'Dilshod'],
    'City': ['Tashkent', 'Samarkand', 'Bukhara', 'Andijan', 'Namangan']
})

# Merge both DataFrames
result = pd.merge(
    orders,
    customers,
    on='CustomerID',
    how='inner'
)

# Display required columns
result = result[
    [
        'OrderID',
        'CustomerID',
        'CustomerName',
        'City',
        'Product',
        'Quantity'
    ]
]

print(result)

   OrderID  CustomerID CustomerName       City              Product  Quantity
0        1         101          Ali   Tashkent               Laptop         2
1        2         102         Vali  Samarkand           Headphones         1
2        3         103        Hasan    Bukhara           Smartphone         3
3        4         101          Ali   Tashkent  External Hard Drive         2
4        5         102         Vali  Samarkand             Backpack         1

Q25. concat() Introduction
Create two small DataFrames manually with the same columns:
StudentID, Name, Score
Then vertically combine them using:
pd.concat()
Requirements:
1.	Use ignore_index=True.
2.	Display the final combined DataFrame.
3.	Explain in a comment why ignore_index=True is useful.

In [86]:
import pandas as pd

# Create first DataFrame
students1 = pd.DataFrame({
    'StudentID': [1, 2, 3],
    'Name': ['Ali', 'Vali', 'Hasan'],
    'Score': [85, 90, 78]
})

# Create second DataFrame
students2 = pd.DataFrame({
    'StudentID': [4, 5, 6],
    'Name': ['Husan', 'Dilshod', 'Jasur'],
    'Score': [88, 92, 81]
})

# Combine both DataFrames vertically
# ignore_index=True creates a new continuous index (0, 1, 2, ...)
# instead of keeping the original indexes from each DataFrame.
result = pd.concat(
    [students1, students2],
    ignore_index=True
)

# Display the final DataFrame
print(result)

   StudentID     Name  Score
0          1      Ali     85
1          2     Vali     90
2          3    Hasan     78
3          4    Husan     88
4          5  Dilshod     92
5          6    Jasur     81