## Homework - 17 Pandas (Introduction, Basics)

### Easy Questions

Q1. Dictionary to DataFrame
Create a dictionary with:
- Names
- Age
- City
(4 rows)
and convert it into a DataFrame named df_manual.

In [6]:
import pandas as pd

data = {
    "Names": ["Ali", "Vali", "Hasan", "Husan"],
    "Age": [21, 24, 20, 23],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan"]
}

df_manual = pd.DataFrame(data)

print(df_manual)

   Names  Age       City
0    Ali   21   Tashkent
1   Vali   24  Samarkand
2  Hasan   20    Bukhara
3  Husan   23    Andijan

Q2. Rename Columns
Using df_manual, rename:
- Names → employee_name
- Age → years_old

In [7]:
df_manual = df_manual.rename(columns={
    "Names": "employee_name",
    "Age": "years_old"
})

print(df_manual)

  employee_name  years_old       City
0           Ali         21   Tashkent
1          Vali         24  Samarkand
2         Hasan         20    Bukhara
3         Husan         23    Andijan

Q3. Display First Rows
Using df_manual, print the first 2 rows using .head().

In [8]:
df_manual.head(2)

  employee_name  years_old       City
0           Ali         21   Tashkent
1          Vali         24  Samarkand

Q4. Mean Age Calculation
Using years_old column from df_manual, calculate the average age.

In [9]:
average = df_manual['years_old'].mean()

print(average)

22.0

Q5. Select Specific Columns
Using df_manual, print only:
- employee_name
- City

In [11]:
df_manual[["employee_name", "City"]]

  employee_name       City
0           Ali   Tashkent
1          Vali  Samarkand
2         Hasan    Bukhara
3         Husan    Andijan

Q6. Load CSV File
Load enterprise_data.csv into a DataFrame named enterprise_df.

In [12]:
enterprise_df = pd.read_csv(r'enterprise_data.csv')
enterprise_df

,First Name,Last Name,Age,City,Department,Monthly Sales,Monthly Expenses,Project_Score,Experience_Years,Is_Remote
0,Employee_0,Family_0,50,Namangan,Marketing,11799,7917,7.3,19,True
1,Employee_1,Family_1,36,Bukhara,Sales,9465,7392,1.7,19,True
2,Employee_2,Family_2,29,Namangan,HR,5635,5952,2.5,5,True
3,Employee_3,Family_3,42,Andijan,HR,6693,2595,3.0,18,True
4,Employee_4,Family_4,40,Namangan,Marketing,14874,7999,3.7,10,False
...,...,...,...,...,...,...,...,...,...,...
115,Employee_115,Family_115,53,Bukhara,HR,8440,6298,7.3,14,False
116,Employee_116,Family_116,53,Bukhara,Finance,8766,4811,4.7,6,False
117,Employee_117,Family_117,25,Andijan,HR,10644,7348,8.9,5,True
118,Employee_118,Family_118,51,Tashkent,Marketing,7914,7795,5.6,11,True
119,Employee_119,Family_119,58,Andijan,HR,9968,3250,9.8,4,False

Q7. Dataset Shape
Using enterprise_df, display the total number of rows and columns using .shape.

In [14]:
enterprise_df.shape

(120, 10)

Q8. Data Types
Using enterprise_df, display data types of all columns using .dtypes.

In [15]:
enterprise_df.dtypes

First Name              str
Last Name               str
Age                   int64
City                    str
Department              str
Monthly Sales         int64
Monthly Expenses      int64
Project_Score       float64
Experience_Years      int64
Is_Remote              bool
dtype: object

Q9. Statistical Summary
Using enterprise_df, apply .describe() on numerical columns.

In [16]:
enterprise_df.describe()

,Age,Monthly Sales,Monthly Expenses,Project_Score,Experience_Years
count,120.000000,120.000000,120.000000,120.000000,120.000000
mean,40.016667,10226.991667,5081.925000,5.423333,10.158333
std,10.991963,2896.314292,1741.885322,2.551741,5.544315
min,22.000000,5412.000000,2133.000000,1.100000,1.000000
25%,30.000000,7825.000000,3379.250000,3.375000,5.000000
50%,40.500000,10182.500000,5140.500000,5.300000,10.500000
75%,48.250000,12566.750000,6733.750000,7.525000,15.000000
max,59.000000,14949.000000,7999.000000,10.000000,19.000000

Q10. Column Names
Print all column names from enterprise_df.

In [17]:
enterprise_df.columns

Index(['First Name', 'Last Name', 'Age', 'City', 'Department', 'Monthly Sales',
       'Monthly Expenses', 'Project_Score', 'Experience_Years', 'Is_Remote'],
      dtype='str')

### Medium Questions

Q11. Add Salary Column
Using df_manual, create a new column named Salary with random values between 3000 and 6000.

In [26]:
import numpy as np

df_manual['Salary'] = np.random.randint(3000, 6001, size=len(df_manual))

df_manual

  employee_name  years_old       City  Salary
0           Ali         21   Tashkent    5009
1          Vali         24  Samarkand    3733
2         Hasan         20    Bukhara    4520
3         Husan         23    Andijan    4949

Q12. Maximum Sales and Expenses
Using Monthly_Sales and Monthly_Expenses columns from enterprise_df, find the maximum values.

In [30]:
max_sales = enterprise_df["Monthly Sales"].max()
max_expenses = enterprise_df["Monthly Expenses"].max()

print("Maximum Sales:", max_sales)
print("Maximum Expenses:", max_expenses)

Maximum Sales: 14949
Maximum Expenses: 7999

Q13. Minimum Sales and Expenses
Using Monthly_Sales and Monthly_Expenses columns from enterprise_df, find the minimum values.

In [75]:
min_sales = enterprise_df["Monthly Sales"].min()
min_expenses = enterprise_df["Monthly Expenses"].min()

print("Minimum Sales:", min_sales)
print("Minimum Expenses:", min_expenses)

Minimum Sales: 5412
Minimum Expenses: 2133

Q14. Average Monthly Sales
Calculate the average value of Monthly_Sales for the entire dataset.

In [35]:
avg_sales = enterprise_df["Monthly Sales"].mean()

print("Average Monthly Sales:", avg_sales)

Average Monthly Sales: 10226.991666666667

Q15. Department as Index
Using Department column, apply .set_index() to make Department the index of enterprise_df.

In [45]:
enterprise_df = enterprise_df.set_index("Department")

enterprise_df

,First Name,Last Name,Age,City,Monthly Sales,Monthly Expenses,Project_Score,Experience_Years,Is_Remote
Department,,,,,,,,,
Marketing,Employee_0,Family_0,50,Namangan,11799,7917,7.3,19,True
Sales,Employee_1,Family_1,36,Bukhara,9465,7392,1.7,19,True
HR,Employee_2,Family_2,29,Namangan,5635,5952,2.5,5,True
HR,Employee_3,Family_3,42,Andijan,6693,2595,3.0,18,True
Marketing,Employee_4,Family_4,40,Namangan,14874,7999,3.7,10,False
...,...,...,...,...,...,...,...,...,...
HR,Employee_115,Family_115,53,Bukhara,8440,6298,7.3,14,False
Finance,Employee_116,Family_116,53,Bukhara,8766,4811,4.7,6,False
HR,Employee_117,Family_117,25,Andijan,10644,7348,8.9,5,True
Marketing,Employee_118,Family_118,51,Tashkent,7914,7795,5.6,11,True
HR,Employee_119,Family_119,58,Andijan,9968,3250,9.8,4,False

Q16. Maximum Project Score by Department
Using Department and Project_Score columns, find the maximum Project_Score for each Department.

In [50]:
result = (
    enterprise_df
    .groupby("Department", as_index=False)["Project_Score"]
    .max()
)

result

  Department  Project_Score
0    Finance            9.1
1         HR            9.8
2         IT            9.8
3  Marketing            9.9
4      Sales           10.0

Q17. Minimum Experience by Department
Using Department and Experience_Years columns, find the minimum Experience_Years for each Department.

In [52]:
result = (
    enterprise_df
    .groupby("Department", as_index=False)["Experience_Years"]
    .min()
)

result

  Department  Experience_Years
0    Finance                 1
1         HR                 3
2         IT                 2
3  Marketing                 1
4      Sales                 1

Q18. Average Expenses by Department
Using Department and Monthly_Expenses columns, calculate average Monthly_Expenses for each Department.

In [53]:
result = (
    enterprise_df
    .groupby("Department", as_index=False)["Monthly Expenses"]
    .mean()
)

result

  Department  Monthly Expenses
0    Finance       5576.818182
1         HR       5236.000000
2         IT       4472.000000
3  Marketing       5117.521739
4      Sales       4987.769231

Q19. Reset Index
Reset the Department index back into a normal column using .reset_index().

In [55]:
enterprise_df = enterprise_df.reset_index("Department")

enterprise_df

,Department,First Name,Last Name,Age,City,Monthly Sales,Monthly Expenses,Project_Score,Experience_Years,Is_Remote
0,Marketing,Employee_0,Family_0,50,Namangan,11799,7917,7.3,19,True
1,Sales,Employee_1,Family_1,36,Bukhara,9465,7392,1.7,19,True
2,HR,Employee_2,Family_2,29,Namangan,5635,5952,2.5,5,True
3,HR,Employee_3,Family_3,42,Andijan,6693,2595,3.0,18,True
4,Marketing,Employee_4,Family_4,40,Namangan,14874,7999,3.7,10,False
...,...,...,...,...,...,...,...,...,...,...
115,HR,Employee_115,Family_115,53,Bukhara,8440,6298,7.3,14,False
116,Finance,Employee_116,Family_116,53,Bukhara,8766,4811,4.7,6,False
117,HR,Employee_117,Family_117,25,Andijan,10644,7348,8.9,5,True
118,Marketing,Employee_118,Family_118,51,Tashkent,7914,7795,5.6,11,True
119,HR,Employee_119,Family_119,58,Andijan,9968,3250,9.8,4,False

Q20. Dataset Transpose
Apply .T (transpose) on the first 5 rows of enterprise_df and observe the output.

In [56]:
enterprise_df.head().T

                           0           1           2           3           4
Department         Marketing       Sales          HR          HR   Marketing
First Name        Employee_0  Employee_1  Employee_2  Employee_3  Employee_4
Last Name           Family_0    Family_1    Family_2    Family_3    Family_4
Age                       50          36          29          42          40
City                Namangan     Bukhara    Namangan     Andijan    Namangan
Monthly Sales          11799        9465        5635        6693       14874
Monthly Expenses        7917        7392        5952        2595        7999
Project_Score            7.3         1.7         2.5         3.0         3.7
Experience_Years          19          19           5          18          10
Is_Remote               True        True        True        True       False

### Hard Questions

Q21. Profitability Intelligence Dashboard — Using enterprise_data.csv, create Profit, Profit Margin, and Efficiency Score columns using Monthly Sales, Monthly Expenses, and Project_Score. Identify top 5 employees by Efficiency Score, detect employees with high sales but low efficiency, rank departments by profitability, and export profitability_dashboard.csv.

In [68]:
import pandas as pd
import numpy as np

# CSV faylni o'qish
enterprise_df = pd.read_csv("enterprise_data.csv")

# 1. Profit ustunini yaratish
enterprise_df["Profit"] = (
    enterprise_df["Monthly Sales"] -
    enterprise_df["Monthly Expenses"]
)

# 2. Profit Margin (%)
enterprise_df["Profit_Margin"] = (
    enterprise_df["Profit"] /
    enterprise_df["Monthly Sales"]
) * 100

# 3. Efficiency Score
enterprise_df["Efficiency_Score"] = (
    enterprise_df["Profit"] *
    enterprise_df["Project_Score"] /
    100
)

# -------------------------------
# Top 5 employees by Efficiency Score
# -------------------------------

top5 = (
    enterprise_df[
        [
            "First Name",
            "Last Name",
            "Department",
            "Efficiency_Score"
        ]
    ]
    .sort_values(by="Efficiency_Score", ascending=False)
    .head(5)
)

print("Top 5 Employees")
print(top5)

# -------------------------------
# High Sales but Low Efficiency
# -------------------------------

high_sales = enterprise_df["Monthly Sales"].median()
low_efficiency = enterprise_df["Efficiency_Score"].median()

low_eff = enterprise_df[
    (enterprise_df["Monthly Sales"] > high_sales) &
    (enterprise_df["Efficiency_Score"] < low_efficiency)
]

print("\nHigh Sales but Low Efficiency")
print(
    low_eff[
        [
            "First Name",
            "Last Name",
            "Department",
            "Monthly Sales",
            "Efficiency_Score"
        ]
    ]
)

# -------------------------------
# Department Profitability Ranking
# -------------------------------

department_profit = (
    enterprise_df
    .groupby("Department", as_index=False)
    .agg(
        Total_Profit=("Profit", "sum"),
        Avg_Profit_Margin=("Profit_Margin", "mean")
    )
    .sort_values(
        by="Total_Profit",
        ascending=False
    )
)

print("\nDepartment Profitability")
print(department_profit)

# -------------------------------
# CSV faylga eksport qilish
# -------------------------------

enterprise_df.to_csv(
    "profitability_dashboard.csv",
    index=False
)

print("\nprofitability_dashboard.csv yaratildi.")

Top 5 Employees
       First Name   Last Name Department  Efficiency_Score
10    Employee_10   Family_10         IT          1107.552
86    Employee_86   Family_86         IT           892.584
101  Employee_101  Family_101         IT           872.476
54    Employee_54   Family_54    Finance           868.791
30    Employee_30   Family_30  Marketing           849.490

High Sales but Low Efficiency
       First Name   Last Name Department  Monthly Sales  Efficiency_Score
11    Employee_11   Family_11         IT          13308           107.055
12    Employee_12   Family_12  Marketing          10949           211.094
21    Employee_21   Family_21  Marketing          12805           192.225
25    Employee_25   Family_25  Marketing          12404           226.352
48    Employee_48   Family_48  Marketing          10881            40.417
49    Employee_49   Family_49         HR          11665           186.428
51    Employee_51   Family_51    Finance          12390           125.749
67    Employee_67   Family_67  Marketing          14760           160.104
80    Employee_80   Family_80         IT          10726           220.416
102  Employee_102  Family_102         IT          10988           128.960
114  Employee_114  Family_114    Finance          12357           183.898

Department Profitability
  Department  Total_Profit  Avg_Profit_Margin
2         IT        141915          55.566772
3  Marketing        140065          50.691150
1         HR        125284          43.402971
0    Finance        120352          44.734702
4      Sales         89792          36.566163

profitability_dashboard.csv yaratildi.

Q22. - read the CSV file into a DataFrame
- print the first 5 rows
- print the last 5 rows
- show the column names
- show the number of rows and columns
- display basic information about the DataFrame
- display summary statistics for numerical columns

In [69]:
import pandas as pd

# CSV faylni o'qish
enterprise_df = pd.read_csv("enterprise_data.csv")

# 1. Birinchi 5 qator
print("First 5 Rows:")
print(enterprise_df.head())

# 2. Oxirgi 5 qator
print("\nLast 5 Rows:")
print(enterprise_df.tail())

# 3. Ustun nomlari
print("\nColumn Names:")
print(enterprise_df.columns)

# 4. Qator va ustunlar soni
print("\nShape:")
print(enterprise_df.shape)

# 5. DataFrame haqida umumiy ma'lumot
print("\nDataFrame Info:")
enterprise_df.info()

# 6. Sonli ustunlar bo'yicha statistik ma'lumotlar
print("\nSummary Statistics:")
print(enterprise_df.describe())

First 5 Rows:
   First Name Last Name  Age      City Department  Monthly Sales  \
0  Employee_0  Family_0   50  Namangan  Marketing          11799
1  Employee_1  Family_1   36   Bukhara      Sales           9465
2  Employee_2  Family_2   29  Namangan         HR           5635
3  Employee_3  Family_3   42   Andijan         HR           6693
4  Employee_4  Family_4   40  Namangan  Marketing          14874

   Monthly Expenses  Project_Score  Experience_Years  Is_Remote
0              7917            7.3                19       True
1              7392            1.7                19       True
2              5952            2.5                 5       True
3              2595            3.0                18       True
4              7999            3.7                10      False

Last 5 Rows:
       First Name   Last Name  Age      City Department  Monthly Sales  \
115  Employee_115  Family_115   53   Bukhara         HR           8440
116  Employee_116  Family_116   53   Bukhara    Finance           8766
117  Employee_117  Family_117   25   Andijan         HR          10644
118  Employee_118  Family_118   51  Tashkent  Marketing           7914
119  Employee_119  Family_119   58   Andijan         HR           9968

     Monthly Expenses  Project_Score  Experience_Years  Is_Remote
115              6298            7.3                14      False
116              4811            4.7                 6      False
117              7348            8.9                 5       True
118              7795            5.6                11       True
119              3250            9.8                 4      False

Column Names:
Index(['First Name', 'Last Name', 'Age', 'City', 'Department', 'Monthly Sales',
       'Monthly Expenses', 'Project_Score', 'Experience_Years', 'Is_Remote'],
      dtype='str')

Shape:
(120, 10)

DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   First Name        120 non-null    str
 1   Last Name         120 non-null    str
 2   Age               120 non-null    int64
 3   City              120 non-null    str
 4   Department        120 non-null    str
 5   Monthly Sales     120 non-null    int64
 6   Monthly Expenses  120 non-null    int64
 7   Project_Score     120 non-null    float64
 8   Experience_Years  120 non-null    int64
 9   Is_Remote         120 non-null    bool
dtypes: bool(1), float64(1), int64(4), str(4)
memory usage: 8.7 KB

Summary Statistics:
              Age  Monthly Sales  Monthly Expenses  Project_Score  \
count  120.000000     120.000000        120.000000     120.000000
mean    40.016667   10226.991667       5081.925000       5.423333
std     10.991963    2896.314292       1741.885322       2.551741
min     22.000000    5412.000000       2133.000000       1.100000
25%     30.000000    7825.000000       3379.250000       3.375000
50%     40.500000   10182.500000       5140.500000       5.300000
75%     48.250000   12566.750000       6733.750000       7.525000
max     59.000000   14949.000000       7999.000000      10.000000

       Experience_Years
count        120.000000
mean          10.158333
std            5.544315
min            1.000000
25%            5.000000
50%           10.500000
75%           15.000000
max           19.000000

Q23. - read the CSV file into a DataFrame
- print only First Name, Last Name, and Department columns
- print only Monthly Sales and Monthly Expenses columns
- create a new column called Full_Name using First Name and Last Name
- create a new column called Profit using Monthly Sales - Monthly Expenses
- print the first 10 rows of the updated DataFrame

In [70]:
import pandas as pd

# CSV faylni o'qish
enterprise_df = pd.read_csv("enterprise_data.csv")

# 1. Faqat First Name, Last Name va Department ustunlarini chiqarish
print("First Name, Last Name va Department:")
print(enterprise_df[["First Name", "Last Name", "Department"]])

# 2. Faqat Monthly Sales va Monthly Expenses ustunlarini chiqarish
print("\nMonthly Sales va Monthly Expenses:")
print(enterprise_df[["Monthly Sales", "Monthly Expenses"]])

# 3. Full_Name ustunini yaratish
enterprise_df["Full_Name"] = (
    enterprise_df["First Name"] + " " + enterprise_df["Last Name"]
)

# 4. Profit ustunini yaratish
enterprise_df["Profit"] = (
    enterprise_df["Monthly Sales"] -
    enterprise_df["Monthly Expenses"]
)

# 5. Yangilangan DataFrame ning birinchi 10 qatorini chiqarish
print("\nUpdated DataFrame (First 10 Rows):")
print(enterprise_df.head(10))

First Name, Last Name va Department:
       First Name   Last Name Department
0      Employee_0    Family_0  Marketing
1      Employee_1    Family_1      Sales
2      Employee_2    Family_2         HR
3      Employee_3    Family_3         HR
4      Employee_4    Family_4  Marketing
..            ...         ...        ...
115  Employee_115  Family_115         HR
116  Employee_116  Family_116    Finance
117  Employee_117  Family_117         HR
118  Employee_118  Family_118  Marketing
119  Employee_119  Family_119         HR

[120 rows x 3 columns]

Monthly Sales va Monthly Expenses:
     Monthly Sales  Monthly Expenses
0            11799              7917
1             9465              7392
2             5635              5952
3             6693              2595
4            14874              7999
..             ...               ...
115           8440              6298
116           8766              4811
117          10644              7348
118           7914              7795
119           9968              3250

[120 rows x 2 columns]

Updated DataFrame (First 10 Rows):
   First Name Last Name  Age       City Department  Monthly Sales  \
0  Employee_0  Family_0   50   Namangan  Marketing          11799
1  Employee_1  Family_1   36    Bukhara      Sales           9465
2  Employee_2  Family_2   29   Namangan         HR           5635
3  Employee_3  Family_3   42    Andijan         HR           6693
4  Employee_4  Family_4   40   Namangan  Marketing          14874
5  Employee_5  Family_5   44    Bukhara      Sales           9752
6  Employee_6  Family_6   32    Bukhara  Marketing          13311
7  Employee_7  Family_7   32    Andijan      Sales           5830
8  Employee_8  Family_8   45  Samarkand    Finance          10177
9  Employee_9  Family_9   57  Samarkand         IT          14561

   Monthly Expenses  Project_Score  Experience_Years  Is_Remote  \
0              7917            7.3                19       True
1              7392            1.7                19       True
2              5952            2.5                 5       True
3              2595            3.0                18       True
4              7999            3.7                10      False
5              2728           10.0                 6      False
6              3365            7.3                 1      False
7              6492            4.5                 5      False
8              2698            7.6                 9       True
9              7731            9.2                12       True

             Full_Name  Profit
0  Employee_0 Family_0    3882
1  Employee_1 Family_1    2073
2  Employee_2 Family_2    -317
3  Employee_3 Family_3    4098
4  Employee_4 Family_4    6875
5  Employee_5 Family_5    7024
6  Employee_6 Family_6    9946
7  Employee_7 Family_7    -662
8  Employee_8 Family_8    7479
9  Employee_9 Family_9    6830

### Easy Questions From Next Topic – Selecting & Filtering

Q24. loc[] Practice
Using .loc[], select:
- Salary
- Department
for employees from index 50 to 60.

In [72]:
import numpy as np

enterprise_df["Salary"] = np.random.randint(
    3000, 10001, size=len(enterprise_df)
)

result = enterprise_df.loc[50:60, ["Salary", "Department"]]

print(result)

    Salary Department
50    6416      Sales
51    8515    Finance
52    4681    Finance
53    4454      Sales
54    4159    Finance
55    9859  Marketing
56    3796         HR
57    9945      Sales
58    8588         HR
59    5810    Finance
60    9616    Finance

Q25. Filtering Practice
Filter enterprise_df for employees where:
- Monthly_Sales > 10000
- Is_Remote == True

In [74]:
filtered_df = enterprise_df[
    (enterprise_df["Monthly Sales"] > 10000) &
    (enterprise_df["Is_Remote"] == True)
]

filtered_df

,First Name,Last Name,Age,City,Department,Monthly Sales,Monthly Expenses,Project_Score,Experience_Years,Is_Remote,Full_Name,Profit,Salary
0,Employee_0,Family_0,50,Namangan,Marketing,11799,7917,7.3,19,True,Employee_0 Family_0,3882,5042
8,Employee_8,Family_8,45,Samarkand,Finance,10177,2698,7.6,9,True,Employee_8 Family_8,7479,8648
9,Employee_9,Family_9,57,Samarkand,IT,14561,7731,9.2,12,True,Employee_9 Family_9,6830,7452
17,Employee_17,Family_17,23,Andijan,HR,14204,6946,4.5,15,True,Employee_17 Family_17,7258,3974
21,Employee_21,Family_21,43,Tashkent,Marketing,12805,6980,3.3,4,True,Employee_21 Family_21,5825,7109
22,Employee_22,Family_22,46,Tashkent,Sales,10237,5140,5.1,1,True,Employee_22 Family_22,5097,9899
28,Employee_28,Family_28,58,Namangan,Marketing,14662,3167,2.2,14,True,Employee_28 Family_28,11495,6870
30,Employee_30,Family_30,42,Bukhara,Marketing,12004,3062,9.5,2,True,Employee_30 Family_30,8942,3089
31,Employee_31,Family_31,30,Bukhara,IT,13130,4156,4.7,13,True,Employee_31 Family_31,8974,5700
38,Employee_38,Family_38,23,Bukhara,Finance,14435,7334,4.7,11,True,Employee_38 Family_38,7101,7173
41,Employee_41,Family_41,28,Tashkent,Marketing,11617,6846,9.9,18,True,Employee_41 Family_41,4771,5808
44,Employee_44,Family_44,35,Andijan,HR,14827,5324,4.5,19,True,Employee_44 Family_44,9503,8336
45,Employee_45,Family_45,38,Andijan,HR,12421,5301,8.5,15,True,Employee_45 Family_45,7120,9159
46,Employee_46,Family_46,57,Samarkand,Finance,14949,3542,6.1,5,True,Employee_46 Family_46,11407,6602
52,Employee_52,Family_52,39,Bukhara,Finance,11905,4681,7.2,17,True,Employee_52 Family_52,7224,4681
54,Employee_54,Family_54,55,Samarkand,Finance,14823,3540,7.7,4,True,Employee_54 Family_54,11283,4159
55,Employee_55,Family_55,31,Samarkand,Marketing,14207,5236,9.2,10,True,Employee_55 Family_55,8971,9859
56,Employee_56,Family_56,57,Andijan,HR,14540,7541,6.3,3,True,Employee_56 Family_56,6999,3796
60,Employee_60,Family_60,29,Bukhara,Finance,10878,3388,3.2,15,True,Employee_60 Family_60,7490,9616
61,Employee_61,Family_61,35,Samarkand,Sales,14087,3856,2.8,4,True,Employee_61 Family_61,10231,3044
62,Employee_62,Family_62,44,Namangan,Marketing,11303,3365,3.3,15,True,Employee_62 Family_62,7938,5693
65,Employee_65,Family_65,39,Andijan,IT,11833,2510,8.9,8,True,Employee_65 Family_65,9323,8976
71,Employee_71,Family_71,22,Samarkand,IT,10732,5486,5.3,9,True,Employee_71 Family_71,5246,10000
73,Employee_73,Family_73,28,Tashkent,IT,13002,4923,3.8,6,True,Employee_73 Family_73,8079,6069
77,Employee_77,Family_77,29,Namangan,Marketing,12723,2713,8.1,5,True,Employee_77 Family_77,10010,9890
82,Employee_82,Family_82,56,Andijan,IT,13945,6268,6.8,4,True,Employee_82 Family_82,7677,9876
84,Employee_84,Family_84,54,Samarkand,Finance,13967,6849,9.1,9,True,Employee_84 Family_84,7118,3062
85,Employee_85,Family_85,26,Bukhara,HR,11748,3243,6.6,3,True,Employee_85 Family_85,8505,4526
86,Employee_86,Family_86,49,Bukhara,IT,14817,5709,9.8,19,True,Employee_86 Family_86,9108,9329
88,Employee_88,Family_88,30,Andijan,HR,13306,7779,6.7,5,True,Employee_88 Family_88,5527,5412
89,Employee_89,Family_89,29,Tashkent,Finance,13808,2455,6.0,4,True,Employee_89 Family_89,11353,3232
93,Employee_93,Family_93,44,Bukhara,Marketing,12668,3958,5.1,4,True,Employee_93 Family_93,8710,7843
100,Employee_100,Family_100,22,Andijan,Finance,12164,5440,8.6,15,True,Employee_100 Family_100,6724,3914
101,Employee_101,Family_101,56,Samarkand,IT,13867,2823,7.9,11,True,Employee_101 Family_101,11044,9679
112,Employee_112,Family_112,36,Tashkent,HR,14879,6175,4.6,12,True,Employee_112 Family_112,8704,8486
113,Employee_113,Family_113,47,Tashkent,HR,11806,4933,7.3,15,True,Employee_113 Family_113,6873,8354
114,Employee_114,Family_114,34,Bukhara,Finance,12357,5284,2.6,1,True,Employee_114 Family_114,7073,9929
117,Employee_117,Family_117,25,Andijan,HR,10644,7348,8.9,5,True,Employee_117 Family_117,3296,9234